In [ ]:
import pandas as pd

# Functions

In [23]:
#1.Reading CSV Files [ by default delimiter is comma (,) ]
df_empy=pd.read_csv('emp.csv')
df_empy

    eno    ename  salary  deptno         doj
0    10    Amber    1000      10  2018-05-14
1     2     Amar    1000      10  2017-03-22
2     8    Sagar    1000      20  2020-11-30
3     4   Thomas    1000      10  2019-08-18
4     5     Jade    2000      10  2021-02-10
5     6    Smith    1000      10  2016-12-01
6     7   Robert    3000      20  2023-06-25
7     3     Nick    1000      30  2015-09-15
8     9    Naman    4000      30  2020-01-20
9     1    Vikas    1000      30  2017-10-03
10   11   Dennis   41000      30  2024-01-05
11   12    Karan    2200      20  2018-06-16
12   13   Simran    1500      10  2019-12-19
13   14     Amit    2000      30  2022-04-09
14   15     Neha    1700      20  2021-07-22
15   16    Rahul    1200      10  2016-03-28
16   17    Divya    3000      30  2015-11-11
17   18   Rakesh    1800      10  2020-09-04
18   19   Monica    2500      20  2023-08-07
19   20     John    2300      30  2018-10-29
20   21    Sneha    2700      10  2022-12-14
21   22    David    1000      20  2017-02-17
22   23    Anita    1500      30  2019-05-21
23   24    Vinod    1800      10  2016-07-30
24   25    Meena    2000      20  2020-03-13
25   26    Harsh    1600      10  2021-09-25
26   27   Kavita    1400      30  2019-01-06
27   28    Mohan    1300      10  2015-04-17
28   29    Priya    1200      20  2023-02-11
29   30   Suresh    1100      10  2018-09-09
30   31     Rani    1900      20  2022-11-03
31   32     Ajay    2100      10  2020-06-26
32   33    Nidhi    2400      30  2016-05-12
33   34    Vivek    2000      20  2017-07-31
34   35    Seema    3000      10  2021-10-15
35   36     Ritu    3200      20  2023-05-01
36   37    Kunal    2800      30  2015-08-22
37   38     Alok    2700      10  2019-03-02
38   39   Poonam    2600      20  2022-02-05
39   40     Yash    2500      30  2020-07-19
40   41     Nina    2300      20  2018-12-28
41   42    Tarun    2200      10  2021-01-09
42   43    Geeta    2100      30  2017-11-14
43   44    Ashok    1900      10  2016-06-08
44   45  Sanjana    1800      20  2023-03-17
45   46    Manoj    1700      30  2019-07-24
46   47    Payal    1600      20  2015-10-10

In [8]:
# Handling Delimiters ( file is separated by space  )--------delimiter-----
df_delimeter =pd.read_csv('file.csv',delimiter = ' ')
df_delimeter

   eno  ename  salary  deptno         doj
0    1  Amber    1000      10  2018-05-14
1    2   Amar    1000      10  2017-03-22

In [11]:
#3. Column and Index Management---------- usecols-----index_col
pd.read_csv('file.csv',delimiter = ' ',usecols = ['eno','ename'],index_col = 'eno',low_memory=False)

     ename
eno
1    Amber
2     Amar

In [34]:
#4. Data Types ( convert the data types of columns and store in dataframe )--------dtypes-----
df_empy.dtypes #read the datatype of all the columns

eno        int64
ename     object
salary     int64
deptno     int64
doj       object
dtype: object

In [38]:
df_delimeter.dtypes

eno        int64
ename     object
salary     int64
deptno     int64
doj       object
dtype: object

In [45]:
df_delimeter_dt = pd.read_csv('file.csv',dtype={'eno':object,'salary':float})
df_delimeter_dt.dtypes

eno ename salary deptno doj    object
dtype: object

In [57]:
df_delimeter_dt_back = pd.read_csv('file.csv',dtype={'eno':int,'salary':int})
df_delimeter_dt_back.dtypes

eno ename salary deptno doj    object
dtype: object

In [65]:
df_empy.tail()  #by default returns last 5 rows

    eno    ename  salary  deptno         doj
37   38     Alok    2700      10  2019-03-02
38   39   Poonam    2600      20  2022-02-05
39   40     Yash    2500      30  2020-07-19
40   41     Nina    2300      20  2018-12-28
41   42    Tarun    2200      10  2021-01-09
42   43    Geeta    2100      30  2017-11-14
43   44    Ashok    1900      10  2016-06-08
44   45  Sanjana    1800      20  2023-03-17
45   46    Manoj    1700      30  2019-07-24
46   47    Payal    1600      20  2015-10-10

In [68]:
df_empy.head() #by default returns last 5 rows
df_empy.head(10) # returns last 10 rows

   eno   ename  salary  deptno         doj
0   10   Amber    1000      10  2018-05-14
1    2    Amar    1000      10  2017-03-22
2    8   Sagar    1000      20  2020-11-30
3    4  Thomas    1000      10  2019-08-18
4    5    Jade    2000      10  2021-02-10
5    6   Smith    1000      10  2016-12-01
6    7  Robert    3000      20  2023-06-25
7    3    Nick    1000      30  2015-09-15
8    9   Naman    4000      30  2020-01-20
9    1   Vikas    1000      30  2017-10-03

In [83]:
df_empy =  pd.read_csv('emp.csv', skiprows=10) #skip fast 10 rows
df_empy

     1    Vikas   1000  30  2017-10-03
0   11   Dennis  41000  30  2024-01-05
1   12    Karan   2200  20  2018-06-16
2   13   Simran   1500  10  2019-12-19
3   14     Amit   2000  30  2022-04-09
4   15     Neha   1700  20  2021-07-22
5   16    Rahul   1200  10  2016-03-28
6   17    Divya   3000  30  2015-11-11
7   18   Rakesh   1800  10  2020-09-04
8   19   Monica   2500  20  2023-08-07
9   20     John   2300  30  2018-10-29
10  21    Sneha   2700  10  2022-12-14
11  22    David   1000  20  2017-02-17
12  23    Anita   1500  30  2019-05-21
13  24    Vinod   1800  10  2016-07-30
14  25    Meena   2000  20  2020-03-13
15  26    Harsh   1600  10  2021-09-25
16  27   Kavita   1400  30  2019-01-06
17  28    Mohan   1300  10  2015-04-17
18  29    Priya   1200  20  2023-02-11
19  30   Suresh   1100  10  2018-09-09
20  31     Rani   1900  20  2022-11-03
21  32     Ajay   2100  10  2020-06-26
22  33    Nidhi   2400  30  2016-05-12
23  34    Vivek   2000  20  2017-07-31
24  35    Seema   3000  10  2021-10-15
25  36     Ritu   3200  20  2023-05-01
26  37    Kunal   2800  30  2015-08-22
27  38     Alok   2700  10  2019-03-02
28  39   Poonam   2600  20  2022-02-05
29  40     Yash   2500  30  2020-07-19
30  41     Nina   2300  20  2018-12-28
31  42    Tarun   2200  10  2021-01-09
32  43    Geeta   2100  30  2017-11-14
33  44    Ashok   1900  10  2016-06-08
34  45  Sanjana   1800  20  2023-03-17
35  46    Manoj   1700  30  2019-07-24
36  47    Payal   1600  20  2015-10-10

In [86]:
df_empy =  pd.read_csv('emp.csv',skiprows=10,nrows=5) #Read a specific number of rows after skipping the initial rows.
df_empy

    1   Vikas   1000  30  2017-10-03
0  11  Dennis  41000  30  2024-01-05
1  12   Karan   2200  20  2018-06-16
2  13  Simran   1500  10  2019-12-19
3  14    Amit   2000  30  2022-04-09
4  15    Neha   1700  20  2021-07-22

In [87]:
df_full_csv=pd.read_csv('emp.csv')
df_full_csv

    eno    ename  salary  deptno         doj
0    10    Amber    1000      10  2018-05-14
1     2     Amar    1000      10  2017-03-22
2     8    Sagar    1000      20  2020-11-30
3     4   Thomas    1000      10  2019-08-18
4     5     Jade    2000      10  2021-02-10
5     6    Smith    1000      10  2016-12-01
6     7   Robert    3000      20  2023-06-25
7     3     Nick    1000      30  2015-09-15
8     9    Naman    4000      30  2020-01-20
9     1    Vikas    1000      30  2017-10-03
10   11   Dennis   41000      30  2024-01-05
11   12    Karan    2200      20  2018-06-16
12   13   Simran    1500      10  2019-12-19
13   14     Amit    2000      30  2022-04-09
14   15     Neha    1700      20  2021-07-22
15   16    Rahul    1200      10  2016-03-28
16   17    Divya    3000      30  2015-11-11
17   18   Rakesh    1800      10  2020-09-04
18   19   Monica    2500      20  2023-08-07
19   20     John    2300      30  2018-10-29
20   21    Sneha    2700      10  2022-12-14
21   22    David    1000      20  2017-02-17
22   23    Anita    1500      30  2019-05-21
23   24    Vinod    1800      10  2016-07-30
24   25    Meena    2000      20  2020-03-13
25   26    Harsh    1600      10  2021-09-25
26   27   Kavita    1400      30  2019-01-06
27   28    Mohan    1300      10  2015-04-17
28   29    Priya    1200      20  2023-02-11
29   30   Suresh    1100      10  2018-09-09
30   31     Rani    1900      20  2022-11-03
31   32     Ajay    2100      10  2020-06-26
32   33    Nidhi    2400      30  2016-05-12
33   34    Vivek    2000      20  2017-07-31
34   35    Seema    3000      10  2021-10-15
35   36     Ritu    3200      20  2023-05-01
36   37    Kunal    2800      30  2015-08-22
37   38     Alok    2700      10  2019-03-02
38   39   Poonam    2600      20  2022-02-05
39   40     Yash    2500      30  2020-07-19
40   41     Nina    2300      20  2018-12-28
41   42    Tarun    2200      10  2021-01-09
42   43    Geeta    2100      30  2017-11-14
43   44    Ashok    1900      10  2016-06-08
44   45  Sanjana    1800      20  2023-03-17
45   46    Manoj    1700      30  2019-07-24
46   47    Payal    1600      20  2015-10-10

In [88]:
df_full_csv[10:20] # Using DataFrame slicing  & Select specific rows by index

    eno   ename  salary  deptno         doj
10   11  Dennis   41000      30  2024-01-05
11   12   Karan    2200      20  2018-06-16
12   13  Simran    1500      10  2019-12-19
13   14    Amit    2000      30  2022-04-09
14   15    Neha    1700      20  2021-07-22
15   16   Rahul    1200      10  2016-03-28
16   17   Divya    3000      30  2015-11-11
17   18  Rakesh    1800      10  2020-09-04
18   19  Monica    2500      20  2023-08-07
19   20    John    2300      30  2018-10-29

In [91]:
df_parse_date =  pd.read_csv('emp.csv',parse_dates = ['doj'])

In [94]:
df_parse_date['doj']

0    2018-05-14
1    2017-03-22
2    2020-11-30
3    2019-08-18
4    2021-02-10
5    2016-12-01
6    2023-06-25
7    2015-09-15
8    2020-01-20
9    2017-10-03
10   2024-01-05
11   2018-06-16
12   2019-12-19
13   2022-04-09
14   2021-07-22
15   2016-03-28
16   2015-11-11
17   2020-09-04
18   2023-08-07
19   2018-10-29
20   2022-12-14
21   2017-02-17
22   2019-05-21
23   2016-07-30
24   2020-03-13
25   2021-09-25
26   2019-01-06
27   2015-04-17
28   2023-02-11
29   2018-09-09
30   2022-11-03
31   2020-06-26
32   2016-05-12
33   2017-07-31
34   2021-10-15
35   2023-05-01
36   2015-08-22
37   2019-03-02
38   2022-02-05
39   2020-07-19
40   2018-12-28
41   2021-01-09
42   2017-11-14
43   2016-06-08
44   2023-03-17
45   2019-07-24
46   2015-10-10
Name: doj, dtype: datetime64[ns]

In [99]:
df_parse_date['doj'].dt.year

0     2018
1     2017
2     2020
3     2019
4     2021
5     2016
6     2023
7     2015
8     2020
9     2017
10    2024
11    2018
12    2019
13    2022
14    2021
15    2016
16    2015
17    2020
18    2023
19    2018
20    2022
21    2017
22    2019
23    2016
24    2020
25    2021
26    2019
27    2015
28    2023
29    2018
30    2022
31    2020
32    2016
33    2017
34    2021
35    2023
36    2015
37    2019
38    2022
39    2020
40    2018
41    2021
42    2017
43    2016
44    2023
45    2019
46    2015
Name: doj, dtype: int32

In [116]:
pd.read_csv('file.csv')

  1 Amber 1000 10 2018-05-14
0  2 Amar 1000 10 2017-03-22

In [122]:
df = pd.read_csv("file.csv",names=['emp_no','emp_name','salary','dept_no','doj'])  #Handling Headers

In [123]:
df

   emp_no emp_name  salary  dept_no          doj
0       1   Amber     1000       10   2018-05-14
1       2    Amar     1000       10   2017-03-22

In [10]:
import pandas as pd

In [13]:
df = pd.read_csv("emp.csv")
df

    eno    ename  salary  deptno         doj
0    10    Amber    1000      10  2018-05-14
1     2     Amar    1000      10  2017-03-22
2     8    Sagar    1000      20  2020-11-30
3     4   Thomas    1000      10  2019-08-18
4     5     Jade    2000      10  2021-02-10
5     6    Smith    1000      10  2016-12-01
6     7   Robert    3000      20  2023-06-25
7     3     Nick    1000      30  2015-09-15
8     9    Naman    4000      30  2020-01-20
9     1    Vikas    1000      30  2017-10-03
10   11   Dennis   41000      30  2024-01-05
11   12    Karan    2200      20  2018-06-16
12   13   Simran    1500      10  2019-12-19
13   14     Amit    2000      30  2022-04-09
14   15     Neha    1700      20  2021-07-22
15   16    Rahul    1200      10  2016-03-28
16   17    Divya    3000      30  2015-11-11
17   18   Rakesh    1800      10  2020-09-04
18   19   Monica    2500      20  2023-08-07
19   20     John    2300      30  2018-10-29
20   21    Sneha    2700      10  2022-12-14
21   22    David    1000      20  2017-02-17
22   23    Anita    1500      30  2019-05-21
23   24    Vinod    1800      10  2016-07-30
24   25    Meena    2000      20  2020-03-13
25   26    Harsh    1600      10  2021-09-25
26   27   Kavita    1400      30  2019-01-06
27   28    Mohan    1300      10  2015-04-17
28   29    Priya    1200      20  2023-02-11
29   30   Suresh    1100      10  2018-09-09
30   31     Rani    1900      20  2022-11-03
31   32     Ajay    2100      10  2020-06-26
32   33    Nidhi    2400      30  2016-05-12
33   34    Vivek    2000      20  2017-07-31
34   35    Seema    3000      10  2021-10-15
35   36     Ritu    3200      20  2023-05-01
36   37    Kunal    2800      30  2015-08-22
37   38     Alok    2700      10  2019-03-02
38   39   Poonam    2600      20  2022-02-05
39   40     Yash    2500      30  2020-07-19
40   41     Nina    2300      20  2018-12-28
41   42    Tarun    2200      10  2021-01-09
42   43    Geeta    2100      30  2017-11-14
43   44    Ashok    1900      10  2016-06-08
44   45  Sanjana    1800      20  2023-03-17
45   46    Manoj    1700      30  2019-07-24
46   47    Payal    1600      20  2015-10-10

In [14]:
type(df) # datatype of df variable

pandas.core.frame.DataFrame

In [15]:
df.dtypes # datatypes of each of the columns in the dataframe

eno        int64
ename     object
salary     int64
deptno     int64
doj       object
dtype: object

In [16]:
column_list = ['eno','ename'] #select( extract ) all the rows from the eno column
column_list

['eno', 'ename']

In [19]:
df[column_list]

    eno    ename
0    10    Amber
1     2     Amar
2     8    Sagar
3     4   Thomas
4     5     Jade
5     6    Smith
6     7   Robert
7     3     Nick
8     9    Naman
9     1    Vikas
10   11   Dennis
11   12    Karan
12   13   Simran
13   14     Amit
14   15     Neha
15   16    Rahul
16   17    Divya
17   18   Rakesh
18   19   Monica
19   20     John
20   21    Sneha
21   22    David
22   23    Anita
23   24    Vinod
24   25    Meena
25   26    Harsh
26   27   Kavita
27   28    Mohan
28   29    Priya
29   30   Suresh
30   31     Rani
31   32     Ajay
32   33    Nidhi
33   34    Vivek
34   35    Seema
35   36     Ritu
36   37    Kunal
37   38     Alok
38   39   Poonam
39   40     Yash
40   41     Nina
41   42    Tarun
42   43    Geeta
43   44    Ashok
44   45  Sanjana
45   46    Manoj
46   47    Payal

In [23]:
row =df.iloc[2]  #select( extract ) a particular row
row

eno                8
ename          Sagar
salary          1000
deptno            20
doj       2020-11-30
Name: 2, dtype: object

In [24]:
type(row)

pandas.core.series.Series

In [25]:
df.iloc[10:20] # select( extract ) few rows

    eno   ename  salary  deptno         doj
10   11  Dennis   41000      30  2024-01-05
11   12   Karan    2200      20  2018-06-16
12   13  Simran    1500      10  2019-12-19
13   14    Amit    2000      30  2022-04-09
14   15    Neha    1700      20  2021-07-22
15   16   Rahul    1200      10  2016-03-28
16   17   Divya    3000      30  2015-11-11
17   18  Rakesh    1800      10  2020-09-04
18   19  Monica    2500      20  2023-08-07
19   20    John    2300      30  2018-10-29

In [43]:
df = pd.read_csv("Text.txt" , delimiter ="\t")
df

Empty DataFrame
Columns: [10\tAmber\t1000\t10\t2018-05-14]
Index: []