# Pandas Day 1 learning

In [1]:
import pandas as pd

In [12]:
df_emp = pd.read_csv("emp.csv")
df_emp

    eno    ename  salary  deptno         doj
0    10    Amber    1000      10  2018-05-14
1     2     Amar    1000      10  2017-03-22
2     8    Sagar    1000      20  2020-11-30
3     4   Thomas    1000      10  2019-08-18
4     5     Jade    2000      10  2021-02-10
5     6    Smith    1000      10  2016-12-01
6     7   Robert    3000      20  2023-06-25
7     3     Nick    1000      30  2015-09-15
8     9    Naman    4000      30  2020-01-20
9     1    Vikas    1000      30  2017-10-03
10   11   Dennis   41000      30  2024-01-05
11   12    Karan    2200      20  2018-06-16
12   13   Simran    1500      10  2019-12-19
13   14     Amit    2000      30  2022-04-09
14   15     Neha    1700      20  2021-07-22
15   16    Rahul    1200      10  2016-03-28
16   17    Divya    3000      30  2015-11-11
17   18   Rakesh    1800      10  2020-09-04
18   19   Monica    2500      20  2023-08-07
19   20     John    2300      30  2018-10-29
20   21    Sneha    2700      10  2022-12-14
21   22    David    1000      20  2017-02-17
22   23    Anita    1500      30  2019-05-21
23   24    Vinod    1800      10  2016-07-30
24   25    Meena    2000      20  2020-03-13
25   26    Harsh    1600      10  2021-09-25
26   27   Kavita    1400      30  2019-01-06
27   28    Mohan    1300      10  2015-04-17
28   29    Priya    1200      20  2023-02-11
29   30   Suresh    1100      10  2018-09-09
30   31     Rani    1900      20  2022-11-03
31   32     Ajay    2100      10  2020-06-26
32   33    Nidhi    2400      30  2016-05-12
33   34    Vivek    2000      20  2017-07-31
34   35    Seema    3000      10  2021-10-15
35   36     Ritu    3200      20  2023-05-01
36   37    Kunal    2800      30  2015-08-22
37   38     Alok    2700      10  2019-03-02
38   39   Poonam    2600      20  2022-02-05
39   40     Yash    2500      30  2020-07-19
40   41     Nina    2300      20  2018-12-28
41   42    Tarun    2200      10  2021-01-09
42   43    Geeta    2100      30  2017-11-14
43   44    Ashok    1900      10  2016-06-08
44   45  Sanjana    1800      20  2023-03-17
45   46    Manoj    1700      30  2019-07-24
46   47    Payal    1600      20  2015-10-10

In [6]:
type(df_emp)

pandas.core.frame.DataFrame

In [21]:
# SQL : select ename from df_emp
series_emp = df_emp['ename']
#print(series_emp)

In [19]:
type(series_emp)

pandas.core.series.Series

In [15]:
# SQL : select ename,salary from df_emp
col_list = ['ename','salary']
df_ename_sal = df_emp[col_list]

In [16]:
type(df_ename_sal)

pandas.core.frame.DataFrame

In [25]:
pd.read_csv("emp1.csv")

   eno ename salary deptno doj
0  10 Amber 1000 10 2018-05-14
1     2 Amar 1000 10 017-03-22

In [26]:
pd.read_csv("emp1.csv",delimiter=" ")

   eno  ename  salary  deptno         doj
0   10  Amber    1000      10  2018-05-14
1    2   Amar    1000      10   017-03-22

In [29]:
df_emp = pd.read_csv("emp.csv",delimiter=",")

In [38]:
# Read the selected columns from the file ( eno,ename)
df_eno_ename = pd.read_csv("emp.csv",delimiter=",",usecols=['eno','ename'])

In [39]:
df_eno_ename

    eno    ename
0    10    Amber
1     2     Amar
2     8    Sagar
3     4   Thomas
4     5     Jade
5     6    Smith
6     7   Robert
7     3     Nick
8     9    Naman
9     1    Vikas
10   11   Dennis
11   12    Karan
12   13   Simran
13   14     Amit
14   15     Neha
15   16    Rahul
16   17    Divya
17   18   Rakesh
18   19   Monica
19   20     John
20   21    Sneha
21   22    David
22   23    Anita
23   24    Vinod
24   25    Meena
25   26    Harsh
26   27   Kavita
27   28    Mohan
28   29    Priya
29   30   Suresh
30   31     Rani
31   32     Ajay
32   33    Nidhi
33   34    Vivek
34   35    Seema
35   36     Ritu
36   37    Kunal
37   38     Alok
38   39   Poonam
39   40     Yash
40   41     Nina
41   42    Tarun
42   43    Geeta
43   44    Ashok
44   45  Sanjana
45   46    Manoj
46   47    Payal

In [42]:
# Read the selected columns from the file ( eno,ename) and set the eno as index field
df_eno_ename = pd.read_csv("emp.csv",delimiter=",",usecols=['eno','ename','salary'],index_col='eno')

In [44]:
# fetch ename column only
# SQL : select ename from emp
df_eno_ename['ename']

eno
10      Amber
2        Amar
8       Sagar
4      Thomas
5        Jade
6       Smith
7      Robert
3        Nick
9       Naman
1       Vikas
11     Dennis
12      Karan
13     Simran
14       Amit
15       Neha
16      Rahul
17      Divya
18     Rakesh
19     Monica
20       John
21      Sneha
22      David
23      Anita
24      Vinod
25      Meena
26      Harsh
27     Kavita
28      Mohan
29      Priya
30     Suresh
31       Rani
32       Ajay
33      Nidhi
34      Vivek
35      Seema
36       Ritu
37      Kunal
38       Alok
39     Poonam
40       Yash
41       Nina
42      Tarun
43      Geeta
44      Ashok
45    Sanjana
46      Manoj
47      Payal
Name: ename, dtype: object

In [48]:
# fetch ename column only
# SQL : select * from emp where eno=43
df_eno_ename.loc[43]

ename     Geeta
salary     2100
Name: 43, dtype: object

In [57]:
df_emp = pd.read_csv("emp.csv",delimiter=",")

In [58]:
df_emp.dtypes

eno        int64
ename     object
salary     int64
deptno     int64
doj       object
dtype: object

In [54]:
df_emp.head(10)

   eno   ename  salary  deptno         doj
0   10   Amber    1000      10  2018-05-14
1    2    Amar    1000      10  2017-03-22
2    8   Sagar    1000      20  2020-11-30
3    4  Thomas    1000      10  2019-08-18
4    5    Jade    2000      10  2021-02-10
5    6   Smith    1000      10  2016-12-01
6    7  Robert    3000      20  2023-06-25
7    3    Nick    1000      30  2015-09-15
8    9   Naman    4000      30  2020-01-20
9    1   Vikas    1000      30  2017-10-03

In [59]:
df_emp.tail()

    eno    ename  salary  deptno         doj
42   43    Geeta    2100      30  2017-11-14
43   44    Ashok    1900      10  2016-06-08
44   45  Sanjana    1800      20  2023-03-17
45   46    Manoj    1700      30  2019-07-24
46   47    Payal    1600      20  2015-10-10

In [60]:
df_emp.dtypes

eno        int64
ename     object
salary     int64
deptno     int64
doj       object
dtype: object

In [63]:
# convert the data type of eno from int to float and salary in to object(str) data type
df_emp = pd.read_csv("emp.csv",delimiter=",",dtype={'eno':float,'salary':object})

In [64]:
df_emp.dtypes

eno       float64
ename      object
salary     object
deptno      int64
doj        object
dtype: object

In [70]:
df_emp['salary']+str(1000)

0      10001000
1      10001000
2      10001000
3      10001000
4      20001000
5      10001000
6      30001000
7      10001000
8      40001000
9      10001000
10    410001000
11     22001000
12     15001000
13     20001000
14     17001000
15     12001000
16     30001000
17     18001000
18     25001000
19     23001000
20     27001000
21     10001000
22     15001000
23     18001000
24     20001000
25     16001000
26     14001000
27     13001000
28     12001000
29     11001000
30     19001000
31     21001000
32     24001000
33     20001000
34     30001000
35     32001000
36     28001000
37     27001000
38     26001000
39     25001000
40     23001000
41     22001000
42     21001000
43     19001000
44     18001000
45     17001000
46     16001000
Name: salary, dtype: object

In [72]:
# convert the data type of eno from int to float
df_emp = pd.read_csv("emp.csv",delimiter=",",dtype={'eno':float})

In [73]:
df_emp.dtypes

eno       float64
ename      object
salary      int64
deptno      int64
doj        object
dtype: object

In [76]:
df_emp['salary']+20

0      1020
1      1020
2      1020
3      1020
4      2020
5      1020
6      3020
7      1020
8      4020
9      1020
10    41020
11     2220
12     1520
13     2020
14     1720
15     1220
16     3020
17     1820
18     2520
19     2320
20     2720
21     1020
22     1520
23     1820
24     2020
25     1620
26     1420
27     1320
28     1220
29     1120
30     1920
31     2120
32     2420
33     2020
34     3020
35     3220
36     2820
37     2720
38     2620
39     2520
40     2320
41     2220
42     2120
43     1920
44     1820
45     1720
46     1620
Name: salary, dtype: int64

In [78]:
df_emp.dtypes

eno       float64
ename      object
salary      int64
deptno      int64
doj        object
dtype: object

In [80]:
df_emp_5 = df_emp.head()

In [82]:
df_emp_5['doj']+"this is date field"

0    2018-05-14this is date field
1    2017-03-22this is date field
2    2020-11-30this is date field
3    2019-08-18this is date field
4    2021-02-10this is date field
Name: doj, dtype: object

In [83]:
df_emp = pd.read_csv("emp.csv",delimiter=",",dtype={'eno':float},parse_dates=['doj'])

In [84]:
df_emp.dtypes

eno              float64
ename             object
salary             int64
deptno             int64
doj       datetime64[ns]
dtype: object

In [90]:
df_emp['doj'].head()

0   2018-05-14
1   2017-03-22
2   2020-11-30
3   2019-08-18
4   2021-02-10
Name: doj, dtype: datetime64[ns]

In [99]:
df_emp['doj'].head().dt.year

df_emp.head(1)

    eno  ename  salary  deptno        doj
0  10.0  Amber    1000      10 2018-05-14

In [97]:
df = pd.read_csv("emp_withoutHeader.csv")

In [96]:
# Assign column names to each columns ( header)

In [102]:
df = pd.read_csv("emp_withoutHeader.csv",names=['emp_no','emp_name','salary','dept_no','doj'])

In [106]:
df.to_csv("emp_processed.csv",index=False)

In [108]:
df_processed = pd.read_csv("emp_processed.csv")

In [109]:
df_processed

    emp_no emp_name  salary  dept_no         doj
0       10    Amber    1000       10  2018-05-14
1        2     Amar    1000       10  2017-03-22
2        8    Sagar    1000       20  2020-11-30
3        4   Thomas    1000       10  2019-08-18
4        5     Jade    2000       10  2021-02-10
5        6    Smith    1000       10  2016-12-01
6        7   Robert    3000       20  2023-06-25
7        3     Nick    1000       30  2015-09-15
8        9    Naman    4000       30  2020-01-20
9        1    Vikas    1000       30  2017-10-03
10      11   Dennis   41000       30  2024-01-05
11      12    Karan    2200       20  2018-06-16
12      13   Simran    1500       10  2019-12-19
13      14     Amit    2000       30  2022-04-09
14      15     Neha    1700       20  2021-07-22
15      16    Rahul    1200       10  2016-03-28
16      17    Divya    3000       30  2015-11-11
17      18   Rakesh    1800       10  2020-09-04
18      19   Monica    2500       20  2023-08-07
19      20     John    2300       30  2018-10-29
20      21    Sneha    2700       10  2022-12-14
21      22    David    1000       20  2017-02-17
22      23    Anita    1500       30  2019-05-21
23      24    Vinod    1800       10  2016-07-30
24      25    Meena    2000       20  2020-03-13
25      26    Harsh    1600       10  2021-09-25
26      27   Kavita    1400       30  2019-01-06
27      28    Mohan    1300       10  2015-04-17
28      29    Priya    1200       20  2023-02-11
29      30   Suresh    1100       10  2018-09-09
30      31     Rani    1900       20  2022-11-03
31      32     Ajay    2100       10  2020-06-26
32      33    Nidhi    2400       30  2016-05-12
33      34    Vivek    2000       20  2017-07-31
34      35    Seema    3000       10  2021-10-15
35      36     Ritu    3200       20  2023-05-01
36      37    Kunal    2800       30  2015-08-22
37      38     Alok    2700       10  2019-03-02
38      39   Poonam    2600       20  2022-02-05
39      40     Yash    2500       30  2020-07-19
40      41     Nina    2300       20  2018-12-28
41      42    Tarun    2200       10  2021-01-09
42      43    Geeta    2100       30  2017-11-14
43      44    Ashok    1900       10  2016-06-08
44      45  Sanjana    1800       20  2023-03-17
45      46    Manoj    1700       30  2019-07-24
46      47    Payal    1600       20  2015-10-10

In [112]:
chunk_no=1
for rec in pd.read_csv("emp.csv",chunksize=10):
    print(chunk_no,"=>",rec)
    chunk_no = chunk_no+1

1 =>    eno   ename  salary  deptno         doj
0   10   Amber    1000      10  2018-05-14
1    2    Amar    1000      10  2017-03-22
2    8   Sagar    1000      20  2020-11-30
3    4  Thomas    1000      10  2019-08-18
4    5    Jade    2000      10  2021-02-10
5    6   Smith    1000      10  2016-12-01
6    7  Robert    3000      20  2023-06-25
7    3    Nick    1000      30  2015-09-15
8    9   Naman    4000      30  2020-01-20
9    1   Vikas    1000      30  2017-10-03
2 =>     eno   ename  salary  deptno         doj
10   11  Dennis   41000      30  2024-01-05
11   12   Karan    2200      20  2018-06-16
12   13  Simran    1500      10  2019-12-19
13   14    Amit    2000      30  2022-04-09
14   15    Neha    1700      20  2021-07-22
15   16   Rahul    1200      10  2016-03-28
16   17   Divya    3000      30  2015-11-11
17   18  Rakesh    1800      10  2020-09-04
18   19  Monica    2500      20  2023-08-07
19   20    John    2300      30  2018-10-29
3 =>     eno   ename  salary  deptno         doj
20   21   Sneha    2700      10  2022-12-14
21   22   David    1000      20  2017-02-17
22   23   Anita    1500      30  2019-05-21
23   24   Vinod    1800      10  2016-07-30
24   25   Meena    2000      20  2020-03-13
25   26   Harsh    1600      10  2021-09-25
26   27  Kavita    1400      30  2019-01-06
27   28   Mohan    1300      10  2015-04-17
28   29   Priya    1200      20  2023-02-11
29   30  Suresh    1100      10  2018-09-09
4 =>     eno   ename  salary  deptno         doj
30   31    Rani    1900      20  2022-11-03
31   32    Ajay    2100      10  2020-06-26
32   33   Nidhi    2400      30  2016-05-12
33   34   Vivek    2000      20  2017-07-31
34   35   Seema    3000      10  2021-10-15
35   36    Ritu    3200      20  2023-05-01
36   37   Kunal    2800      30  2015-08-22
37   38    Alok    2700      10  2019-03-02
38   39  Poonam    2600      20  2022-02-05
39   40    Yash    2500      30  2020-07-19
5 =>     eno    ename  salary  deptno         doj
40   41     Nina    2300      20  2018-12-28
41   42    Tarun    2200      10  2021-01-09
42   43    Geeta    2100      30  2017-11-14
43   44    Ashok    1900      10  2016-06-08
44   45  Sanjana    1800      20  2023-03-17
45   46    Manoj    1700      30  2019-07-24
46   47    Payal    1600      20  2015-10-10

In [116]:
# Read from row no. 10 to 20
df.head(20).tail(10)

    emp_no emp_name  salary  dept_no         doj
10      11   Dennis   41000       30  2024-01-05
11      12    Karan    2200       20  2018-06-16
12      13   Simran    1500       10  2019-12-19
13      14     Amit    2000       30  2022-04-09
14      15     Neha    1700       20  2021-07-22
15      16    Rahul    1200       10  2016-03-28
16      17    Divya    3000       30  2015-11-11
17      18   Rakesh    1800       10  2020-09-04
18      19   Monica    2500       20  2023-08-07
19      20     John    2300       30  2018-10-29

In [123]:
df = pd.read_csv("emp.csv",skiprows=1,nrows=10)

In [124]:
df

   10   Amber   1000  10.1  2018-05-14
0   2    Amar   1000    10  2017-03-22
1   8   Sagar   1000    20  2020-11-30
2   4  Thomas   1000    10  2019-08-18
3   5    Jade   2000    10  2021-02-10
4   6   Smith   1000    10  2016-12-01
5   7  Robert   3000    20  2023-06-25
6   3    Nick   1000    30  2015-09-15
7   9   Naman   4000    30  2020-01-20
8   1   Vikas   1000    30  2017-10-03
9  11  Dennis  41000    30  2024-01-05