# Different Files handling

In [1]:
import pandas as pd
df_emp = pd.read_csv("emp.csv")
df_emp.count()

eID      20
ename    20
dtype: int64

In [3]:
df_sal = pd.read_csv("salary.txt")
df_sal.count()

eno       20
salary    20
dtype: int64

In [4]:
# Vertical concatenation ( axis = 1)

pd.concat([df_emp,df_sal],axis=0)

       eID           ename     eno   salary
0   1001.0     Aarav Mehta     NaN      NaN
1   1002.0     Isha Sharma     NaN      NaN
2   1003.0      Rajiv Nair     NaN      NaN
3   1004.0     Kavya Reddy     NaN      NaN
4   1005.0    Aditya Patel     NaN      NaN
5   1006.0      Priya Iyer     NaN      NaN
6   1007.0     Arjun Singh     NaN      NaN
7   1008.0      Neha Verma     NaN      NaN
8   1009.0   Devansh Desai     NaN      NaN
9   1010.0    Ananya Joshi     NaN      NaN
10  1011.0    Rohan Kapoor     NaN      NaN
11  1012.0     Simran Kaur     NaN      NaN
12  1013.0      Ayan Dutta     NaN      NaN
13  1014.0    Tanya Bansal     NaN      NaN
14  1015.0  Manav Malhotra     NaN      NaN
15  2001.0      Shruti Rao     NaN      NaN
16  2002.0     Kunal Dixit     NaN      NaN
17  2003.0     Sanya Dubey     NaN      NaN
18  2010.0    Harshit Jain     NaN      NaN
19  2011.0    Ritika Ghosh     NaN      NaN
0      NaN             NaN  1001.0  52000.0
1      NaN             NaN  1002.0  61000.0
2      NaN             NaN  1003.0  48000.0
3      NaN             NaN  1004.0  75000.0
4      NaN             NaN  1005.0  56000.0
5      NaN             NaN  1006.0  64000.0
6      NaN             NaN  1007.0  59000.0
7      NaN             NaN  1008.0  67000.0
8      NaN             NaN  1009.0  73000.0
9      NaN             NaN  1010.0  50000.0
10     NaN             NaN  1011.0  62000.0
11     NaN             NaN  1012.0  71000.0
12     NaN             NaN  1013.0  55000.0
13     NaN             NaN  1014.0  58000.0
14     NaN             NaN  1015.0  69000.0
15     NaN             NaN  1016.0  53000.0
16     NaN             NaN  1017.0  57000.0
17     NaN             NaN  1018.0  66000.0
18     NaN             NaN  3001.0  60000.0
19     NaN             NaN  3002.0  72000.0

In [5]:
# Vertical concatenation ( axis = 1)

pd.concat([df_emp,df_sal],axis=1)

     eID           ename   eno  salary
0   1001     Aarav Mehta  1001   52000
1   1002     Isha Sharma  1002   61000
2   1003      Rajiv Nair  1003   48000
3   1004     Kavya Reddy  1004   75000
4   1005    Aditya Patel  1005   56000
5   1006      Priya Iyer  1006   64000
6   1007     Arjun Singh  1007   59000
7   1008      Neha Verma  1008   67000
8   1009   Devansh Desai  1009   73000
9   1010    Ananya Joshi  1010   50000
10  1011    Rohan Kapoor  1011   62000
11  1012     Simran Kaur  1012   71000
12  1013      Ayan Dutta  1013   55000
13  1014    Tanya Bansal  1014   58000
14  1015  Manav Malhotra  1015   69000
15  2001      Shruti Rao  1016   53000
16  2002     Kunal Dixit  1017   57000
17  2003     Sanya Dubey  1018   66000
18  2010    Harshit Jain  3001   60000
19  2011    Ritika Ghosh  3002   72000

In [92]:
df_emp1 = pd.read_csv("emp.csv")
df_emp2 = pd.read_csv("emp.csv")

# Union
df = pd.concat([df_emp1,df_emp2],axis=0)

# Union without duplicates
df = pd.concat([df_emp1,df_emp2],axis=0).drop_duplicates()

# Intersection
df_concat = pd.concat([df_emp1, df_emp2], axis=0)

df_duplicated = df_concat[df_concat.duplicated(keep=False)]
df_unique = df_duplicated.drop_duplicates()
df_unique

     eid           ename
0   1002     Isha Sharma
1   1003      Rajiv Nair
2   1001     Aarav Mehta
3   1004     Kavya Reddy
4   1005    Aditya Patel
5   1006      Priya Iyer
6   1007     Arjun Singh
7   1008      Neha Verma
8   1009   Devansh Desai
9   1010    Ananya Joshi
10  1011    Rohan Kapoor
11  1012     Simran Kaur
12  1013      Ayan Dutta
13  1014    Tanya Bansal
14  1015  Manav Malhotra
15  2001      Shruti Rao
16  2002     Kunal Dixit
17  2003     Sanya Dubey
18  2010    Harshit Jain
19  2011    Ritika Ghosh

     eid           ename
0   1002     Isha Sharma
1   1003      Rajiv Nair
2   1001     Aarav Mehta
3   1004     Kavya Reddy
4   1005    Aditya Patel
5   1006      Priya Iyer
6   1007     Arjun Singh
7   1008      Neha Verma
8   1009   Devansh Desai
9   1010    Ananya Joshi
10  1011    Rohan Kapoor
11  1012     Simran Kaur
12  1013      Ayan Dutta
13  1014    Tanya Bansal
14  1015  Manav Malhotra
15  2001      Shruti Rao
16  2002     Kunal Dixit
17  2003     Sanya Dubey
18  2010    Harshit Jain
19  2011    Ritika Ghosh

     eid           ename
0   1002     Isha Sharma
1   1003      Rajiv Nair
2   1001     Aarav Mehta
3   1004     Kavya Reddy
4   1005    Aditya Patel
5   1006      Priya Iyer
6   1007     Arjun Singh
7   1008      Neha Verma
8   1009   Devansh Desai
9   1010    Ananya Joshi
10  1011    Rohan Kapoor
11  1012     Simran Kaur
12  1013      Ayan Dutta
13  1014    Tanya Bansal
14  1015  Manav Malhotra
15  2001      Shruti Rao
16  2002     Kunal Dixit
17  2003     Sanya Dubey
18  2010    Harshit Jain
19  2011    Ritika Ghosh
0   1002     Isha Sharma
1   1003      Rajiv Nair
2   1001     Aarav Mehta
3   1004     Kavya Reddy
4   1005    Aditya Patel
5   1006      Priya Iyer
6   1007     Arjun Singh
7   1008      Neha Verma
8   1009   Devansh Desai
9   1010    Ananya Joshi
10  1011    Rohan Kapoor
11  1012     Simran Kaur
12  1013      Ayan Dutta
13  1014    Tanya Bansal
14  1015  Manav Malhotra
15  2001      Shruti Rao
16  2002     Kunal Dixit
17  2003     Sanya Dubey
18  2010    Harshit Jain
19  2011    Ritika Ghosh

In [8]:
# save the employees data in parquet file
df_emp.to_parquet("emp.parquet",engine='pyarrow')

In [9]:
df = pd.read_parquet("emp.parquet") # Read the employees data in parquet file

In [10]:
# Read Excel data 
pd.read_excel("employees_excel_data.XLSX",sheet_name='Sheet2')

   eno ename
0    6     A
1    7     B
2    8     C
3    9     D
4   10     E

In [6]:
df_emp1 = pd.read_csv("emp.csv")
df_emp2 = pd.read_csv("emp.csv")

In [15]:
df =pd.concat([df_emp1,df_emp2],axis = 0).drop_duplicates()  # Union without duplicates
df

     eID           ename
0   1001     Aarav Mehta
1   1002     Isha Sharma
2   1003      Rajiv Nair
3   1004     Kavya Reddy
4   1005    Aditya Patel
5   1006      Priya Iyer
6   1007     Arjun Singh
7   1008      Neha Verma
8   1009   Devansh Desai
9   1010    Ananya Joshi
10  1011    Rohan Kapoor
11  1012     Simran Kaur
12  1013      Ayan Dutta
13  1014    Tanya Bansal
14  1015  Manav Malhotra
15  2001      Shruti Rao
16  2002     Kunal Dixit
17  2003     Sanya Dubey
18  2010    Harshit Jain
19  2011    Ritika Ghosh

# Database Connectivity

In [2]:
# Syntax 
# pd.read_sql("query","connection_info")
from sqlalchemy import create_engine
import Oracledb

mysql_engine = create_engine("mysql+pymysql://root:Admin%40123@localhost:3306/etl")

oracle_engine = create_engine("oracle+oracledb://system:Admin@localhost:1521/xe")

query_mysql = "select * from Customers"

query_oracle = "select * from customers"

oracle_conn = oracledb.connect

ModuleNotFoundError: No module named 'Oracledb'

In [19]:
# Mysql database
df = pd.read_sql(query_mysql,mysql_engine)

In [13]:
df

   CustomerID     Name             Phone
0        C001    Alice   +1-123-456-7890
1        C002      Bob   +1-987-654-3210
2        C003  Charlie   +1-555-123-4567
3        C004    David   +1-222-333-4444
4        C005     Emma   +1-444-555-6666
5        C006    Frank   +1-333-444-5555
6        C007    Grace   +1-888-777-6666
7        C008   Hannah   +1-111-222-3333
8        C009      Ian   +1-999-888-7777
9        C010     Jack   +1-765-432-1000
10       C011    Karen   +1-555-666-7777
11       C012      Leo   +1-222-333-4444
12       C013      Mia   +1-111-333-5555
13       C014     Noah   +1-123-456-7890
14       C015   Olivia   +1-321-654-0987
15      C0200     Noah  +91-123-456-7890
16      C0201   Olivia  +44-321-654-0987

In [14]:
# Oracle database
df = pd.read_sql(query_oracle,oracle_engine)

In [15]:
df

    eno           ename        doj   salary  commission
0     1      Ram Sharma 2020-01-15  60000.0      5000.0
1     2      Amit Verma 2020-02-10  70000.0      7000.0
2     3      Neha Gupta 2020-03-05  55000.0      3000.0
3     4     Rohit Mehta 2020-04-18  72000.0      6000.0
4     5     Pooja Singh 2020-05-20  48000.0      2000.0
5     6     Ankit Patel 2020-06-12  64000.0      4000.0
6     7      Sneha Iyer 2020-07-08  58000.0      3500.0
7     8  Karan Malhotra 2020-08-22  62000.0      4500.0
8     9      Priya Nair 2020-09-14  75000.0      8000.0
9    10     Vikas Reddy 2020-10-30  67000.0      5500.0
10   11    Deepak Joshi 2020-11-25  73000.0      6200.0
11   12       Ritu Kaur 2020-12-18  49000.0         NaN
12   13    Suresh Yadav 2021-01-10  71000.0         NaN
13   14    Nidhi Bansal 2021-02-05  54000.0      3100.0
14   15     Manoj Kumar 2021-03-12  59000.0      2900.0
15   16   Rakesh Mishra 2021-04-08  65000.0      3600.0
16   17      Sunita Rao 2021-05-19  77000.0      7500.0
17   18     Ajay Khanna 2021-06-23  52000.0      2500.0
18   19    Kavita Desai 2021-07-15  64000.0      3200.0
19   20    Arjun Chawla 2021-08-28  60000.0      5000.0

In [16]:
# Read the data from mysql table and write in to oracle table
# Read the data from mysql table 
df = pd.read_sql(query_mysql,mysql_engine)

# write the data to oracle table
df.to_sql("customer_info",oracle_engine,index=False)

ValueError: Table 'customer_info' already exists.

In [ ]:
# Way 2 using oracledb
oracle_conn = oracledb.connect(
    password="admin",
     user="system",
    dsn="localhost:1521/xe"
)

df = pd.read_sql(query_oracle,con=oracle_conn)
df

# Scenario 1: Source data in mysql database and target in oracle database . I need to complare if both source and target are exactly matching

In [26]:
from sqlalchemy import create_engine
import cx_Oracle
import oracledb

mysql_engine_src = create_engine("mysql+pymysql://root:Admin%40143@localhost:3308/nov25_db")

oracle_engine_tgt = create_engine("oracle+cx_oracle://system:admin@localhost:1521/xe")

query_mysql_src = "select * from customer_processed where CustomerID ='C001'"

query_oracle_tgt = "select * from customer_info"

In [27]:
df_src = pd.read_sql(query_mysql_src,mysql_engine_src)
df_tgt = pd.read_sql(query_oracle_tgt,oracle_engine_tgt)

In [28]:
if df_src.equals(df_tgt) == False:
    print("data between source and target doesn not match")
else:
    print("data macthes - Passed")

data between source and target doesn not match

In [ ]:
assert df_src.equals(df_tgt),"data between source and target doesn not match"

In [30]:
df_src

  CustomerID   Name            Phone
0       C001  Alice  +1-123-456-7890

In [25]:
df_tgt

   CustomerID     Name             Phone
0        C001    Alice   +1-123-456-7890
1        C002      Bob   +1-987-654-3210
2        C003  Charlie   +1-555-123-4567
3        C004    David   +1-222-333-4444
4        C005     Emma   +1-444-555-6666
5        C006    Frank   +1-333-444-5555
6        C007    Grace   +1-888-777-6666
7        C008   Hannah   +1-111-222-3333
8        C009      Ian   +1-999-888-7777
9        C010     Jack   +1-765-432-1000
10       C011    Karen   +1-555-666-7777
11       C012      Leo   +1-222-333-4444
12       C013      Mia   +1-111-333-5555
13       C014     Noah   +1-123-456-7890
14       C015   Olivia   +1-321-654-0987
15      C0200     Noah  +91-123-456-7890
16      C0201   Olivia  +44-321-654-0987

In [53]:
status = df_src['CustomerID'].isin(df_tgt['CustomerID'])

In [56]:
count_matched = status.sum()

In [59]:
assert count_matched > 0 ,"No mactched"

AssertionError: No mactched

In [60]:
status = df_src['CustomerID'].equals(df_tgt['CustomerID'])