# Filter ( where caluse in sql)

In [ ]:
import pandas as pd
df = pd.read_csv("emp_details.csv")

In [9]:
# Filter ( where clause in SQL)
# Q1 . Get me all the employees for deptno = 10
# SQL  select * from emp where deptno=10
deptno_10 = df['deptno'] == 10
df[deptno_10]

     eno           ename         doj  deptno  salary
0   1001    Arjun Sharma  2022-01-15      10    1000
6   1007     Vijay Singh  2022-07-08      10    1000
12  1013  Shivani Sharma  2022-09-13      10   74363
18  1019      Meera Nair  2020-09-17      10    1000
20  1021  Prakash Pillai  2022-12-11      10   73569
26  1027   Harshit Kumar  2022-08-16      10   66535
32  1033     Suresh Jain  2021-12-01      10   69234
38  1039      Ajit Reddy  2022-04-18      10   69399
44  1045    Pankaj Joshi  2022-06-10      10   70445

In [13]:
# Filter ( where clause in SQL)
# Q1 . Get me all the employees ther than  deptno = 10
# SQL  select * from emp where deptno!=10
deptno_10 = df['deptno'] == 10
df[~deptno_10]

     eno               ename         doj  deptno  salary
1   1002         Priya Patel  2023-03-22      20   67387
2   1003          Ravi Kumar  2021-05-10      30   70421
3   1004         Sneha Gupta  2020-08-25      40   68902
4   1005          Anil Reddy  2024-02-13      50   78005
5   1006          Neha Verma  2019-11-30      60   59843
7   1008         Ananya Iyer  2021-03-15      20   74625
8   1009        Manish Joshi  2020-12-19      30   67560
9   1010         Simran Kaur  2023-01-11      40   68902
10  1011        Rajesh Mehta  2021-09-01      50   62497
11  1012       Deepika Desai  2020-06-10      60   70179
13  1014         Harish Nair  2023-04-01      20   61487
14  1015         Komal Yadav  2021-11-23      30   61894
15  1016          Ajay Bhatt  2020-04-25      40   70109
16  1017         Pooja Malik  2022-02-28      50   77450
17  1018        Raghav Joshi  2021-06-14      60   62873
19  1020         Krishna Rao  2023-10-02      20    2000
21  1022  Aishwarya Deshmukh  2021-07-25      20   69746
22  1023          Vikas Soni  2020-11-15      30   60933
23  1024          Ritu Mehra  2023-05-20      40   67801
24  1025       Nitin Chauhan  2020-03-30      50   66948
25  1026        Swati Kapoor  2021-10-05      60   66972
27  1028       Kanika Thakur  2020-01-10      20   67752
28  1029      Arvind Agarwal  2023-02-18      30   70986
29  1030         Divya Singh  2021-04-22      40   67845
30  1031        Akash Prasad  2020-06-05      50   72594
31  1032          Geeta Rani  2022-09-07      60   63916
33  1034          Sonal Shah  2023-08-13      20    2000
34  1035       Jayesh Bansal  2020-02-15      30   69811
35  1036        Shweta Yadav  2021-06-03      40   63559
36  1037      Rajendra Joshi  2023-11-19      50   73561
37  1038        Kavita Mehta  2020-07-25      60   71892
39  1040     Pratibha Sharma  2021-09-05      20   65072
40  1041     Subodh Tripathi  2020-05-14      30   68215
41  1042        Sunita Gupta  2023-03-09      40   72534
42  1043        Arvind Kumar  2021-08-22      50   70019
43  1044      Neeraj Agarwal  2020-02-19      60   69312
45  1046          Suman Iyer  2023-04-28      20   67751
46  1047         Sunil Verma  2020-09-14      30   66989
47  1048       Meenal Pandey  2021-07-03      40   66228
48  1049          Manju Nair  2022-11-17      50   69061
49  1050       Sandeep Yadav  2021-10-12      60   60921

In [14]:
# Filter ( where clause in SQL)
# Q1 . Get me all the employees for deptno = 10 or 20
# SQL  select * from emp where deptno in (10,20)
deptno_10 = df['deptno'] == 10
deptno_20 = df['deptno'] == 20
deptno_10_and_20 = deptno_10 | deptno_20
df[deptno_10_and_20]

     eno               ename         doj  deptno  salary
0   1001        Arjun Sharma  2022-01-15      10    1000
1   1002         Priya Patel  2023-03-22      20   67387
6   1007         Vijay Singh  2022-07-08      10    1000
7   1008         Ananya Iyer  2021-03-15      20   74625
12  1013      Shivani Sharma  2022-09-13      10   74363
13  1014         Harish Nair  2023-04-01      20   61487
18  1019          Meera Nair  2020-09-17      10    1000
19  1020         Krishna Rao  2023-10-02      20    2000
20  1021      Prakash Pillai  2022-12-11      10   73569
21  1022  Aishwarya Deshmukh  2021-07-25      20   69746
26  1027       Harshit Kumar  2022-08-16      10   66535
27  1028       Kanika Thakur  2020-01-10      20   67752
32  1033         Suresh Jain  2021-12-01      10   69234
33  1034          Sonal Shah  2023-08-13      20    2000
38  1039          Ajit Reddy  2022-04-18      10   69399
39  1040     Pratibha Sharma  2021-09-05      20   65072
44  1045        Pankaj Joshi  2022-06-10      10   70445
45  1046          Suman Iyer  2023-04-28      20   67751

In [18]:
# Filter ( where clause in SQL)
# Q1 . Get me all the employees for deptno = 10 whose salaey is less than or equal 10,00
# SQL  select * from emp where deptno= 10 and salary <=10000
deptno_10 = df['deptno'] == 10
salary = df['salary'] <= 1000
final_filter = deptno_10 & salary
df[final_filter]

     eno         ename         doj  deptno  salary
0   1001  Arjun Sharma  2022-01-15      10    1000
6   1007   Vijay Singh  2022-07-08      10    1000
18  1019    Meera Nair  2020-09-17      10    1000

In [26]:
# Filter ( where clause in SQL)
# Q1 . Get me all the employees for deptno = 10 whose salary not equals equal to 10,00
# SQL  select * from emp where deptno= 10 and salary !=1000
deptno_10 = df['deptno'] == 10
salary = df['salary'] == 1000
salary = ~salary
final_filter = deptno_10 & salary
df[final_filter]

     eno           ename         doj  deptno  salary
12  1013  Shivani Sharma  2022-09-13      10   74363
20  1021  Prakash Pillai  2022-12-11      10   73569
26  1027   Harshit Kumar  2022-08-16      10   66535
32  1033     Suresh Jain  2021-12-01      10   69234
38  1039      Ajit Reddy  2022-04-18      10   69399
44  1045    Pankaj Joshi  2022-06-10      10   70445

# Sorting the data in ascending or descending order

In [34]:
# Sorting can be done in two diffrent ways : sort_values or sort_index
# Q1 : sort the employess rows in ascending order of salary ( lowest to highest salary)
# SQL : select * from emp order by salary asc
df.sort_values(by='salary',ascending=True)

     eno               ename         doj  deptno  salary
0   1001        Arjun Sharma  2022-01-15      10    1000
18  1019          Meera Nair  2020-09-17      10    1000
6   1007         Vijay Singh  2022-07-08      10    1000
33  1034          Sonal Shah  2023-08-13      20    2000
19  1020         Krishna Rao  2023-10-02      20    2000
5   1006          Neha Verma  2019-11-30      60   59843
49  1050       Sandeep Yadav  2021-10-12      60   60921
22  1023          Vikas Soni  2020-11-15      30   60933
13  1014         Harish Nair  2023-04-01      20   61487
14  1015         Komal Yadav  2021-11-23      30   61894
10  1011        Rajesh Mehta  2021-09-01      50   62497
17  1018        Raghav Joshi  2021-06-14      60   62873
35  1036        Shweta Yadav  2021-06-03      40   63559
31  1032          Geeta Rani  2022-09-07      60   63916
39  1040     Pratibha Sharma  2021-09-05      20   65072
47  1048       Meenal Pandey  2021-07-03      40   66228
26  1027       Harshit Kumar  2022-08-16      10   66535
24  1025       Nitin Chauhan  2020-03-30      50   66948
25  1026        Swati Kapoor  2021-10-05      60   66972
46  1047         Sunil Verma  2020-09-14      30   66989
1   1002         Priya Patel  2023-03-22      20   67387
8   1009        Manish Joshi  2020-12-19      30   67560
45  1046          Suman Iyer  2023-04-28      20   67751
27  1028       Kanika Thakur  2020-01-10      20   67752
23  1024          Ritu Mehra  2023-05-20      40   67801
29  1030         Divya Singh  2021-04-22      40   67845
40  1041     Subodh Tripathi  2020-05-14      30   68215
9   1010         Simran Kaur  2023-01-11      40   68902
3   1004         Sneha Gupta  2020-08-25      40   68902
48  1049          Manju Nair  2022-11-17      50   69061
32  1033         Suresh Jain  2021-12-01      10   69234
43  1044      Neeraj Agarwal  2020-02-19      60   69312
38  1039          Ajit Reddy  2022-04-18      10   69399
21  1022  Aishwarya Deshmukh  2021-07-25      20   69746
34  1035       Jayesh Bansal  2020-02-15      30   69811
42  1043        Arvind Kumar  2021-08-22      50   70019
15  1016          Ajay Bhatt  2020-04-25      40   70109
11  1012       Deepika Desai  2020-06-10      60   70179
2   1003          Ravi Kumar  2021-05-10      30   70421
44  1045        Pankaj Joshi  2022-06-10      10   70445
28  1029      Arvind Agarwal  2023-02-18      30   70986
37  1038        Kavita Mehta  2020-07-25      60   71892
41  1042        Sunita Gupta  2023-03-09      40   72534
30  1031        Akash Prasad  2020-06-05      50   72594
36  1037      Rajendra Joshi  2023-11-19      50   73561
20  1021      Prakash Pillai  2022-12-11      10   73569
12  1013      Shivani Sharma  2022-09-13      10   74363
7   1008         Ananya Iyer  2021-03-15      20   74625
16  1017         Pooja Malik  2022-02-28      50   77450
4   1005          Anil Reddy  2024-02-13      50   78005

In [35]:
# Sorting can be done in two diffrent ways : sort_values or sort_index
# Q1 : sort the employess rows in descending order of salary ( higest to lowest salary)
# SQL : select * from emp order by salary desc
df.sort_values(by='salary',ascending=False)

     eno               ename         doj  deptno  salary
4   1005          Anil Reddy  2024-02-13      50   78005
16  1017         Pooja Malik  2022-02-28      50   77450
7   1008         Ananya Iyer  2021-03-15      20   74625
12  1013      Shivani Sharma  2022-09-13      10   74363
20  1021      Prakash Pillai  2022-12-11      10   73569
36  1037      Rajendra Joshi  2023-11-19      50   73561
30  1031        Akash Prasad  2020-06-05      50   72594
41  1042        Sunita Gupta  2023-03-09      40   72534
37  1038        Kavita Mehta  2020-07-25      60   71892
28  1029      Arvind Agarwal  2023-02-18      30   70986
44  1045        Pankaj Joshi  2022-06-10      10   70445
2   1003          Ravi Kumar  2021-05-10      30   70421
11  1012       Deepika Desai  2020-06-10      60   70179
15  1016          Ajay Bhatt  2020-04-25      40   70109
42  1043        Arvind Kumar  2021-08-22      50   70019
34  1035       Jayesh Bansal  2020-02-15      30   69811
21  1022  Aishwarya Deshmukh  2021-07-25      20   69746
38  1039          Ajit Reddy  2022-04-18      10   69399
43  1044      Neeraj Agarwal  2020-02-19      60   69312
32  1033         Suresh Jain  2021-12-01      10   69234
48  1049          Manju Nair  2022-11-17      50   69061
9   1010         Simran Kaur  2023-01-11      40   68902
3   1004         Sneha Gupta  2020-08-25      40   68902
40  1041     Subodh Tripathi  2020-05-14      30   68215
29  1030         Divya Singh  2021-04-22      40   67845
23  1024          Ritu Mehra  2023-05-20      40   67801
27  1028       Kanika Thakur  2020-01-10      20   67752
45  1046          Suman Iyer  2023-04-28      20   67751
8   1009        Manish Joshi  2020-12-19      30   67560
1   1002         Priya Patel  2023-03-22      20   67387
46  1047         Sunil Verma  2020-09-14      30   66989
25  1026        Swati Kapoor  2021-10-05      60   66972
24  1025       Nitin Chauhan  2020-03-30      50   66948
26  1027       Harshit Kumar  2022-08-16      10   66535
47  1048       Meenal Pandey  2021-07-03      40   66228
39  1040     Pratibha Sharma  2021-09-05      20   65072
31  1032          Geeta Rani  2022-09-07      60   63916
35  1036        Shweta Yadav  2021-06-03      40   63559
17  1018        Raghav Joshi  2021-06-14      60   62873
10  1011        Rajesh Mehta  2021-09-01      50   62497
14  1015         Komal Yadav  2021-11-23      30   61894
13  1014         Harish Nair  2023-04-01      20   61487
22  1023          Vikas Soni  2020-11-15      30   60933
49  1050       Sandeep Yadav  2021-10-12      60   60921
5   1006          Neha Verma  2019-11-30      60   59843
33  1034          Sonal Shah  2023-08-13      20    2000
19  1020         Krishna Rao  2023-10-02      20    2000
18  1019          Meera Nair  2020-09-17      10    1000
6   1007         Vijay Singh  2022-07-08      10    1000
0   1001        Arjun Sharma  2022-01-15      10    1000

In [36]:
# Q1 : sort the employess rows in ascending order of deptno and descending order of salary
# SQL : select * from emp order by deptno asc,salary desc
df.sort_values(by=['deptno','salary'],ascending=[True,False])

     eno               ename         doj  deptno  salary
12  1013      Shivani Sharma  2022-09-13      10   74363
20  1021      Prakash Pillai  2022-12-11      10   73569
44  1045        Pankaj Joshi  2022-06-10      10   70445
38  1039          Ajit Reddy  2022-04-18      10   69399
32  1033         Suresh Jain  2021-12-01      10   69234
26  1027       Harshit Kumar  2022-08-16      10   66535
0   1001        Arjun Sharma  2022-01-15      10    1000
6   1007         Vijay Singh  2022-07-08      10    1000
18  1019          Meera Nair  2020-09-17      10    1000
7   1008         Ananya Iyer  2021-03-15      20   74625
21  1022  Aishwarya Deshmukh  2021-07-25      20   69746
27  1028       Kanika Thakur  2020-01-10      20   67752
45  1046          Suman Iyer  2023-04-28      20   67751
1   1002         Priya Patel  2023-03-22      20   67387
39  1040     Pratibha Sharma  2021-09-05      20   65072
13  1014         Harish Nair  2023-04-01      20   61487
19  1020         Krishna Rao  2023-10-02      20    2000
33  1034          Sonal Shah  2023-08-13      20    2000
28  1029      Arvind Agarwal  2023-02-18      30   70986
2   1003          Ravi Kumar  2021-05-10      30   70421
34  1035       Jayesh Bansal  2020-02-15      30   69811
40  1041     Subodh Tripathi  2020-05-14      30   68215
8   1009        Manish Joshi  2020-12-19      30   67560
46  1047         Sunil Verma  2020-09-14      30   66989
14  1015         Komal Yadav  2021-11-23      30   61894
22  1023          Vikas Soni  2020-11-15      30   60933
41  1042        Sunita Gupta  2023-03-09      40   72534
15  1016          Ajay Bhatt  2020-04-25      40   70109
3   1004         Sneha Gupta  2020-08-25      40   68902
9   1010         Simran Kaur  2023-01-11      40   68902
29  1030         Divya Singh  2021-04-22      40   67845
23  1024          Ritu Mehra  2023-05-20      40   67801
47  1048       Meenal Pandey  2021-07-03      40   66228
35  1036        Shweta Yadav  2021-06-03      40   63559
4   1005          Anil Reddy  2024-02-13      50   78005
16  1017         Pooja Malik  2022-02-28      50   77450
36  1037      Rajendra Joshi  2023-11-19      50   73561
30  1031        Akash Prasad  2020-06-05      50   72594
42  1043        Arvind Kumar  2021-08-22      50   70019
48  1049          Manju Nair  2022-11-17      50   69061
24  1025       Nitin Chauhan  2020-03-30      50   66948
10  1011        Rajesh Mehta  2021-09-01      50   62497
37  1038        Kavita Mehta  2020-07-25      60   71892
11  1012       Deepika Desai  2020-06-10      60   70179
43  1044      Neeraj Agarwal  2020-02-19      60   69312
25  1026        Swati Kapoor  2021-10-05      60   66972
31  1032          Geeta Rani  2022-09-07      60   63916
17  1018        Raghav Joshi  2021-06-14      60   62873
49  1050       Sandeep Yadav  2021-10-12      60   60921
5   1006          Neha Verma  2019-11-30      60   59843

In [37]:
# sort_index => sorting the data based on index column

In [51]:
df_emp = pd.read_csv("emp_details.csv",index_col ='eno')

In [54]:
# Q1 sort the data in ascending order of eno( the index column)
df_emp.sort_index()
# or 
df_emp.sort_index(ascending = True)

                   ename         doj  deptno  salary
eno
1001        Arjun Sharma  2022-01-15      10    1000
1002         Priya Patel  2023-03-22      20   67387
1003          Ravi Kumar  2021-05-10      30   70421
1004         Sneha Gupta  2020-08-25      40   68902
1005          Anil Reddy  2024-02-13      50   78005
1006          Neha Verma  2019-11-30      60   59843
1007         Vijay Singh  2022-07-08      10    1000
1008         Ananya Iyer  2021-03-15      20   74625
1009        Manish Joshi  2020-12-19      30   67560
1010         Simran Kaur  2023-01-11      40   68902
1011        Rajesh Mehta  2021-09-01      50   62497
1012       Deepika Desai  2020-06-10      60   70179
1013      Shivani Sharma  2022-09-13      10   74363
1014         Harish Nair  2023-04-01      20   61487
1015         Komal Yadav  2021-11-23      30   61894
1016          Ajay Bhatt  2020-04-25      40   70109
1017         Pooja Malik  2022-02-28      50   77450
1018        Raghav Joshi  2021-06-14      60   62873
1019          Meera Nair  2020-09-17      10    1000
1020         Krishna Rao  2023-10-02      20    2000
1021      Prakash Pillai  2022-12-11      10   73569
1022  Aishwarya Deshmukh  2021-07-25      20   69746
1023          Vikas Soni  2020-11-15      30   60933
1024          Ritu Mehra  2023-05-20      40   67801
1025       Nitin Chauhan  2020-03-30      50   66948
1026        Swati Kapoor  2021-10-05      60   66972
1027       Harshit Kumar  2022-08-16      10   66535
1028       Kanika Thakur  2020-01-10      20   67752
1029      Arvind Agarwal  2023-02-18      30   70986
1030         Divya Singh  2021-04-22      40   67845
1031        Akash Prasad  2020-06-05      50   72594
1032          Geeta Rani  2022-09-07      60   63916
1033         Suresh Jain  2021-12-01      10   69234
1034          Sonal Shah  2023-08-13      20    2000
1035       Jayesh Bansal  2020-02-15      30   69811
1036        Shweta Yadav  2021-06-03      40   63559
1037      Rajendra Joshi  2023-11-19      50   73561
1038        Kavita Mehta  2020-07-25      60   71892
1039          Ajit Reddy  2022-04-18      10   69399
1040     Pratibha Sharma  2021-09-05      20   65072
1041     Subodh Tripathi  2020-05-14      30   68215
1042        Sunita Gupta  2023-03-09      40   72534
1043        Arvind Kumar  2021-08-22      50   70019
1044      Neeraj Agarwal  2020-02-19      60   69312
1045        Pankaj Joshi  2022-06-10      10   70445
1046          Suman Iyer  2023-04-28      20   67751
1047         Sunil Verma  2020-09-14      30   66989
1048       Meenal Pandey  2021-07-03      40   66228
1049          Manju Nair  2022-11-17      50   69061
1050       Sandeep Yadav  2021-10-12      60   60921

In [55]:
# Q sort the data in descending order of eno( the index column)

df_emp.sort_index(ascending = False)

                   ename         doj  deptno  salary
eno
1050       Sandeep Yadav  2021-10-12      60   60921
1049          Manju Nair  2022-11-17      50   69061
1048       Meenal Pandey  2021-07-03      40   66228
1047         Sunil Verma  2020-09-14      30   66989
1046          Suman Iyer  2023-04-28      20   67751
1045        Pankaj Joshi  2022-06-10      10   70445
1044      Neeraj Agarwal  2020-02-19      60   69312
1043        Arvind Kumar  2021-08-22      50   70019
1042        Sunita Gupta  2023-03-09      40   72534
1041     Subodh Tripathi  2020-05-14      30   68215
1040     Pratibha Sharma  2021-09-05      20   65072
1039          Ajit Reddy  2022-04-18      10   69399
1038        Kavita Mehta  2020-07-25      60   71892
1037      Rajendra Joshi  2023-11-19      50   73561
1036        Shweta Yadav  2021-06-03      40   63559
1035       Jayesh Bansal  2020-02-15      30   69811
1034          Sonal Shah  2023-08-13      20    2000
1033         Suresh Jain  2021-12-01      10   69234
1032          Geeta Rani  2022-09-07      60   63916
1031        Akash Prasad  2020-06-05      50   72594
1030         Divya Singh  2021-04-22      40   67845
1029      Arvind Agarwal  2023-02-18      30   70986
1028       Kanika Thakur  2020-01-10      20   67752
1027       Harshit Kumar  2022-08-16      10   66535
1026        Swati Kapoor  2021-10-05      60   66972
1025       Nitin Chauhan  2020-03-30      50   66948
1024          Ritu Mehra  2023-05-20      40   67801
1023          Vikas Soni  2020-11-15      30   60933
1022  Aishwarya Deshmukh  2021-07-25      20   69746
1021      Prakash Pillai  2022-12-11      10   73569
1020         Krishna Rao  2023-10-02      20    2000
1019          Meera Nair  2020-09-17      10    1000
1018        Raghav Joshi  2021-06-14      60   62873
1017         Pooja Malik  2022-02-28      50   77450
1016          Ajay Bhatt  2020-04-25      40   70109
1015         Komal Yadav  2021-11-23      30   61894
1014         Harish Nair  2023-04-01      20   61487
1013      Shivani Sharma  2022-09-13      10   74363
1012       Deepika Desai  2020-06-10      60   70179
1011        Rajesh Mehta  2021-09-01      50   62497
1010         Simran Kaur  2023-01-11      40   68902
1009        Manish Joshi  2020-12-19      30   67560
1008         Ananya Iyer  2021-03-15      20   74625
1007         Vijay Singh  2022-07-08      10    1000
1006          Neha Verma  2019-11-30      60   59843
1005          Anil Reddy  2024-02-13      50   78005
1004         Sneha Gupta  2020-08-25      40   68902
1003          Ravi Kumar  2021-05-10      30   70421
1002         Priya Patel  2023-03-22      20   67387
1001        Arjun Sharma  2022-01-15      10    1000

In [56]:
# Q sort the data in descending order of eno( the index column)

df_emp.sort_index(ascending = False)

                   ename         doj  deptno  salary
eno
1050       Sandeep Yadav  2021-10-12      60   60921
1049          Manju Nair  2022-11-17      50   69061
1048       Meenal Pandey  2021-07-03      40   66228
1047         Sunil Verma  2020-09-14      30   66989
1046          Suman Iyer  2023-04-28      20   67751
1045        Pankaj Joshi  2022-06-10      10   70445
1044      Neeraj Agarwal  2020-02-19      60   69312
1043        Arvind Kumar  2021-08-22      50   70019
1042        Sunita Gupta  2023-03-09      40   72534
1041     Subodh Tripathi  2020-05-14      30   68215
1040     Pratibha Sharma  2021-09-05      20   65072
1039          Ajit Reddy  2022-04-18      10   69399
1038        Kavita Mehta  2020-07-25      60   71892
1037      Rajendra Joshi  2023-11-19      50   73561
1036        Shweta Yadav  2021-06-03      40   63559
1035       Jayesh Bansal  2020-02-15      30   69811
1034          Sonal Shah  2023-08-13      20    2000
1033         Suresh Jain  2021-12-01      10   69234
1032          Geeta Rani  2022-09-07      60   63916
1031        Akash Prasad  2020-06-05      50   72594
1030         Divya Singh  2021-04-22      40   67845
1029      Arvind Agarwal  2023-02-18      30   70986
1028       Kanika Thakur  2020-01-10      20   67752
1027       Harshit Kumar  2022-08-16      10   66535
1026        Swati Kapoor  2021-10-05      60   66972
1025       Nitin Chauhan  2020-03-30      50   66948
1024          Ritu Mehra  2023-05-20      40   67801
1023          Vikas Soni  2020-11-15      30   60933
1022  Aishwarya Deshmukh  2021-07-25      20   69746
1021      Prakash Pillai  2022-12-11      10   73569
1020         Krishna Rao  2023-10-02      20    2000
1019          Meera Nair  2020-09-17      10    1000
1018        Raghav Joshi  2021-06-14      60   62873
1017         Pooja Malik  2022-02-28      50   77450
1016          Ajay Bhatt  2020-04-25      40   70109
1015         Komal Yadav  2021-11-23      30   61894
1014         Harish Nair  2023-04-01      20   61487
1013      Shivani Sharma  2022-09-13      10   74363
1012       Deepika Desai  2020-06-10      60   70179
1011        Rajesh Mehta  2021-09-01      50   62497
1010         Simran Kaur  2023-01-11      40   68902
1009        Manish Joshi  2020-12-19      30   67560
1008         Ananya Iyer  2021-03-15      20   74625
1007         Vijay Singh  2022-07-08      10    1000
1006          Neha Verma  2019-11-30      60   59843
1005          Anil Reddy  2024-02-13      50   78005
1004         Sneha Gupta  2020-08-25      40   68902
1003          Ravi Kumar  2021-05-10      30   70421
1002         Priya Patel  2023-03-22      20   67387
1001        Arjun Sharma  2022-01-15      10    1000

In [57]:
df_emp

                   ename         doj  deptno  salary
eno
1003          Ravi Kumar  2021-05-10      30   70421
1002         Priya Patel  2023-03-22      20   67387
1001        Arjun Sharma  2022-01-15      10    1000
1004         Sneha Gupta  2020-08-25      40   68902
1005          Anil Reddy  2024-02-13      50   78005
1006          Neha Verma  2019-11-30      60   59843
1007         Vijay Singh  2022-07-08      10    1000
1008         Ananya Iyer  2021-03-15      20   74625
1009        Manish Joshi  2020-12-19      30   67560
1010         Simran Kaur  2023-01-11      40   68902
1011        Rajesh Mehta  2021-09-01      50   62497
1012       Deepika Desai  2020-06-10      60   70179
1013      Shivani Sharma  2022-09-13      10   74363
1014         Harish Nair  2023-04-01      20   61487
1015         Komal Yadav  2021-11-23      30   61894
1016          Ajay Bhatt  2020-04-25      40   70109
1017         Pooja Malik  2022-02-28      50   77450
1018        Raghav Joshi  2021-06-14      60   62873
1019          Meera Nair  2020-09-17      10    1000
1020         Krishna Rao  2023-10-02      20    2000
1021      Prakash Pillai  2022-12-11      10   73569
1022  Aishwarya Deshmukh  2021-07-25      20   69746
1023          Vikas Soni  2020-11-15      30   60933
1024          Ritu Mehra  2023-05-20      40   67801
1025       Nitin Chauhan  2020-03-30      50   66948
1026        Swati Kapoor  2021-10-05      60   66972
1027       Harshit Kumar  2022-08-16      10   66535
1028       Kanika Thakur  2020-01-10      20   67752
1029      Arvind Agarwal  2023-02-18      30   70986
1030         Divya Singh  2021-04-22      40   67845
1031        Akash Prasad  2020-06-05      50   72594
1032          Geeta Rani  2022-09-07      60   63916
1033         Suresh Jain  2021-12-01      10   69234
1034          Sonal Shah  2023-08-13      20    2000
1035       Jayesh Bansal  2020-02-15      30   69811
1036        Shweta Yadav  2021-06-03      40   63559
1037      Rajendra Joshi  2023-11-19      50   73561
1038        Kavita Mehta  2020-07-25      60   71892
1039          Ajit Reddy  2022-04-18      10   69399
1040     Pratibha Sharma  2021-09-05      20   65072
1041     Subodh Tripathi  2020-05-14      30   68215
1042        Sunita Gupta  2023-03-09      40   72534
1043        Arvind Kumar  2021-08-22      50   70019
1044      Neeraj Agarwal  2020-02-19      60   69312
1045        Pankaj Joshi  2022-06-10      10   70445
1046          Suman Iyer  2023-04-28      20   67751
1047         Sunil Verma  2020-09-14      30   66989
1048       Meenal Pandey  2021-07-03      40   66228
1049          Manju Nair  2022-11-17      50   69061
1050       Sandeep Yadav  2021-10-12      60   60921

In [58]:
# Q. sort the data in descending order of eno( the index column) and store in a dataframe

df_result = df_emp.sort_index(ascending = False)

In [59]:
df_result

                   ename         doj  deptno  salary
eno
1050       Sandeep Yadav  2021-10-12      60   60921
1049          Manju Nair  2022-11-17      50   69061
1048       Meenal Pandey  2021-07-03      40   66228
1047         Sunil Verma  2020-09-14      30   66989
1046          Suman Iyer  2023-04-28      20   67751
1045        Pankaj Joshi  2022-06-10      10   70445
1044      Neeraj Agarwal  2020-02-19      60   69312
1043        Arvind Kumar  2021-08-22      50   70019
1042        Sunita Gupta  2023-03-09      40   72534
1041     Subodh Tripathi  2020-05-14      30   68215
1040     Pratibha Sharma  2021-09-05      20   65072
1039          Ajit Reddy  2022-04-18      10   69399
1038        Kavita Mehta  2020-07-25      60   71892
1037      Rajendra Joshi  2023-11-19      50   73561
1036        Shweta Yadav  2021-06-03      40   63559
1035       Jayesh Bansal  2020-02-15      30   69811
1034          Sonal Shah  2023-08-13      20    2000
1033         Suresh Jain  2021-12-01      10   69234
1032          Geeta Rani  2022-09-07      60   63916
1031        Akash Prasad  2020-06-05      50   72594
1030         Divya Singh  2021-04-22      40   67845
1029      Arvind Agarwal  2023-02-18      30   70986
1028       Kanika Thakur  2020-01-10      20   67752
1027       Harshit Kumar  2022-08-16      10   66535
1026        Swati Kapoor  2021-10-05      60   66972
1025       Nitin Chauhan  2020-03-30      50   66948
1024          Ritu Mehra  2023-05-20      40   67801
1023          Vikas Soni  2020-11-15      30   60933
1022  Aishwarya Deshmukh  2021-07-25      20   69746
1021      Prakash Pillai  2022-12-11      10   73569
1020         Krishna Rao  2023-10-02      20    2000
1019          Meera Nair  2020-09-17      10    1000
1018        Raghav Joshi  2021-06-14      60   62873
1017         Pooja Malik  2022-02-28      50   77450
1016          Ajay Bhatt  2020-04-25      40   70109
1015         Komal Yadav  2021-11-23      30   61894
1014         Harish Nair  2023-04-01      20   61487
1013      Shivani Sharma  2022-09-13      10   74363
1012       Deepika Desai  2020-06-10      60   70179
1011        Rajesh Mehta  2021-09-01      50   62497
1010         Simran Kaur  2023-01-11      40   68902
1009        Manish Joshi  2020-12-19      30   67560
1008         Ananya Iyer  2021-03-15      20   74625
1007         Vijay Singh  2022-07-08      10    1000
1006          Neha Verma  2019-11-30      60   59843
1005          Anil Reddy  2024-02-13      50   78005
1004         Sneha Gupta  2020-08-25      40   68902
1003          Ravi Kumar  2021-05-10      30   70421
1002         Priya Patel  2023-03-22      20   67387
1001        Arjun Sharma  2022-01-15      10    1000

                   ename         doj  deptno  salary
eno
1003          Ravi Kumar  2021-05-10      30   70421
1002         Priya Patel  2023-03-22      20   67387
1001        Arjun Sharma  2022-01-15      10    1000
1004         Sneha Gupta  2020-08-25      40   68902
1005          Anil Reddy  2024-02-13      50   78005
1006          Neha Verma  2019-11-30      60   59843
1007         Vijay Singh  2022-07-08      10    1000
1008         Ananya Iyer  2021-03-15      20   74625
1009        Manish Joshi  2020-12-19      30   67560
1010         Simran Kaur  2023-01-11      40   68902
1011        Rajesh Mehta  2021-09-01      50   62497
1012       Deepika Desai  2020-06-10      60   70179
1013      Shivani Sharma  2022-09-13      10   74363
1014         Harish Nair  2023-04-01      20   61487
1015         Komal Yadav  2021-11-23      30   61894
1016          Ajay Bhatt  2020-04-25      40   70109
1017         Pooja Malik  2022-02-28      50   77450
1018        Raghav Joshi  2021-06-14      60   62873
1019          Meera Nair  2020-09-17      10    1000
1020         Krishna Rao  2023-10-02      20    2000
1021      Prakash Pillai  2022-12-11      10   73569
1022  Aishwarya Deshmukh  2021-07-25      20   69746
1023          Vikas Soni  2020-11-15      30   60933
1024          Ritu Mehra  2023-05-20      40   67801
1025       Nitin Chauhan  2020-03-30      50   66948
1026        Swati Kapoor  2021-10-05      60   66972
1027       Harshit Kumar  2022-08-16      10   66535
1028       Kanika Thakur  2020-01-10      20   67752
1029      Arvind Agarwal  2023-02-18      30   70986
1030         Divya Singh  2021-04-22      40   67845
1031        Akash Prasad  2020-06-05      50   72594
1032          Geeta Rani  2022-09-07      60   63916
1033         Suresh Jain  2021-12-01      10   69234
1034          Sonal Shah  2023-08-13      20    2000
1035       Jayesh Bansal  2020-02-15      30   69811
1036        Shweta Yadav  2021-06-03      40   63559
1037      Rajendra Joshi  2023-11-19      50   73561
1038        Kavita Mehta  2020-07-25      60   71892
1039          Ajit Reddy  2022-04-18      10   69399
1040     Pratibha Sharma  2021-09-05      20   65072
1041     Subodh Tripathi  2020-05-14      30   68215
1042        Sunita Gupta  2023-03-09      40   72534
1043        Arvind Kumar  2021-08-22      50   70019
1044      Neeraj Agarwal  2020-02-19      60   69312
1045        Pankaj Joshi  2022-06-10      10   70445
1046          Suman Iyer  2023-04-28      20   67751
1047         Sunil Verma  2020-09-14      30   66989
1048       Meenal Pandey  2021-07-03      40   66228
1049          Manju Nair  2022-11-17      50   69061
1050       Sandeep Yadav  2021-10-12      60   60921

In [61]:
# Q. sort the data in descending order of eno( the index column) and save in the same dataframe

df_emp.sort_index(ascending = False,inplace=True)

In [62]:
df_emp

                   ename         doj  deptno  salary
eno
1050       Sandeep Yadav  2021-10-12      60   60921
1049          Manju Nair  2022-11-17      50   69061
1048       Meenal Pandey  2021-07-03      40   66228
1047         Sunil Verma  2020-09-14      30   66989
1046          Suman Iyer  2023-04-28      20   67751
1045        Pankaj Joshi  2022-06-10      10   70445
1044      Neeraj Agarwal  2020-02-19      60   69312
1043        Arvind Kumar  2021-08-22      50   70019
1042        Sunita Gupta  2023-03-09      40   72534
1041     Subodh Tripathi  2020-05-14      30   68215
1040     Pratibha Sharma  2021-09-05      20   65072
1039          Ajit Reddy  2022-04-18      10   69399
1038        Kavita Mehta  2020-07-25      60   71892
1037      Rajendra Joshi  2023-11-19      50   73561
1036        Shweta Yadav  2021-06-03      40   63559
1035       Jayesh Bansal  2020-02-15      30   69811
1034          Sonal Shah  2023-08-13      20    2000
1033         Suresh Jain  2021-12-01      10   69234
1032          Geeta Rani  2022-09-07      60   63916
1031        Akash Prasad  2020-06-05      50   72594
1030         Divya Singh  2021-04-22      40   67845
1029      Arvind Agarwal  2023-02-18      30   70986
1028       Kanika Thakur  2020-01-10      20   67752
1027       Harshit Kumar  2022-08-16      10   66535
1026        Swati Kapoor  2021-10-05      60   66972
1025       Nitin Chauhan  2020-03-30      50   66948
1024          Ritu Mehra  2023-05-20      40   67801
1023          Vikas Soni  2020-11-15      30   60933
1022  Aishwarya Deshmukh  2021-07-25      20   69746
1021      Prakash Pillai  2022-12-11      10   73569
1020         Krishna Rao  2023-10-02      20    2000
1019          Meera Nair  2020-09-17      10    1000
1018        Raghav Joshi  2021-06-14      60   62873
1017         Pooja Malik  2022-02-28      50   77450
1016          Ajay Bhatt  2020-04-25      40   70109
1015         Komal Yadav  2021-11-23      30   61894
1014         Harish Nair  2023-04-01      20   61487
1013      Shivani Sharma  2022-09-13      10   74363
1012       Deepika Desai  2020-06-10      60   70179
1011        Rajesh Mehta  2021-09-01      50   62497
1010         Simran Kaur  2023-01-11      40   68902
1009        Manish Joshi  2020-12-19      30   67560
1008         Ananya Iyer  2021-03-15      20   74625
1007         Vijay Singh  2022-07-08      10    1000
1006          Neha Verma  2019-11-30      60   59843
1005          Anil Reddy  2024-02-13      50   78005
1004         Sneha Gupta  2020-08-25      40   68902
1003          Ravi Kumar  2021-05-10      30   70421
1002         Priya Patel  2023-03-22      20   67387
1001        Arjun Sharma  2022-01-15      10    1000

# Grouping the data

In [64]:
df = pd.read_csv("emp_details.csv")

In [66]:
df.sort_values(by='deptno')

     eno               ename         doj  deptno  salary
26  1027       Harshit Kumar  2022-08-16      10   66535
2   1001        Arjun Sharma  2022-01-15      10    1000
32  1033         Suresh Jain  2021-12-01      10   69234
20  1021      Prakash Pillai  2022-12-11      10   73569
6   1007         Vijay Singh  2022-07-08      10    1000
18  1019          Meera Nair  2020-09-17      10    1000
38  1039          Ajit Reddy  2022-04-18      10   69399
44  1045        Pankaj Joshi  2022-06-10      10   70445
12  1013      Shivani Sharma  2022-09-13      10   74363
27  1028       Kanika Thakur  2020-01-10      20   67752
21  1022  Aishwarya Deshmukh  2021-07-25      20   69746
19  1020         Krishna Rao  2023-10-02      20    2000
39  1040     Pratibha Sharma  2021-09-05      20   65072
13  1014         Harish Nair  2023-04-01      20   61487
7   1008         Ananya Iyer  2021-03-15      20   74625
33  1034          Sonal Shah  2023-08-13      20    2000
1   1002         Priya Patel  2023-03-22      20   67387
45  1046          Suman Iyer  2023-04-28      20   67751
14  1015         Komal Yadav  2021-11-23      30   61894
28  1029      Arvind Agarwal  2023-02-18      30   70986
34  1035       Jayesh Bansal  2020-02-15      30   69811
8   1009        Manish Joshi  2020-12-19      30   67560
46  1047         Sunil Verma  2020-09-14      30   66989
22  1023          Vikas Soni  2020-11-15      30   60933
40  1041     Subodh Tripathi  2020-05-14      30   68215
0   1003          Ravi Kumar  2021-05-10      30   70421
29  1030         Divya Singh  2021-04-22      40   67845
41  1042        Sunita Gupta  2023-03-09      40   72534
15  1016          Ajay Bhatt  2020-04-25      40   70109
9   1010         Simran Kaur  2023-01-11      40   68902
47  1048       Meenal Pandey  2021-07-03      40   66228
3   1004         Sneha Gupta  2020-08-25      40   68902
23  1024          Ritu Mehra  2023-05-20      40   67801
35  1036        Shweta Yadav  2021-06-03      40   63559
42  1043        Arvind Kumar  2021-08-22      50   70019
36  1037      Rajendra Joshi  2023-11-19      50   73561
24  1025       Nitin Chauhan  2020-03-30      50   66948
30  1031        Akash Prasad  2020-06-05      50   72594
48  1049          Manju Nair  2022-11-17      50   69061
16  1017         Pooja Malik  2022-02-28      50   77450
10  1011        Rajesh Mehta  2021-09-01      50   62497
4   1005          Anil Reddy  2024-02-13      50   78005
37  1038        Kavita Mehta  2020-07-25      60   71892
25  1026        Swati Kapoor  2021-10-05      60   66972
17  1018        Raghav Joshi  2021-06-14      60   62873
43  1044      Neeraj Agarwal  2020-02-19      60   69312
11  1012       Deepika Desai  2020-06-10      60   70179
5   1006          Neha Verma  2019-11-30      60   59843
31  1032          Geeta Rani  2022-09-07      60   63916
49  1050       Sandeep Yadav  2021-10-12      60   60921

In [78]:
# Q. Get me the count of employees in each department
# SQL : select deptno,count(deptno) from emp group by deptno

grouped_data = df.groupby('deptno')['eno'].count()

In [73]:
type(grouped_data)

pandas.core.series.Series

In [80]:
grouped_data_df = grouped_data.reset_index()

In [81]:
type(grouped_data_df)

pandas.core.frame.DataFrame

In [89]:
grouped_data_df.rename(columns = {'eno':"total_employee","deptno":"Department_number"},inplace=True)

In [90]:
grouped_data_df

   Department_number  total_employee
0                 10               9
1                 20               9
2                 30               8
3                 40               8
4                 50               8
5                 60               8

In [ ]:
# Common agrregate function : sum(),mean(),count(),max(),min()

In [104]:
# Q1 . Get me the count of employees, total_salary,max_salary,min_salary per department
# SQL : select deptno,count(*),sum(sal),max(sal),min(sal) from emp group by deptno
grped_df = df.groupby('deptno')['salary'].agg(['sum','max','min','count']).reset_index()

grped_df.rename(columns = {"sum":"Total_salary","max":"Maximun_salary","min":"Minimum_salary","count":"employees count"},inplace=True)

In [106]:
grped_df

   deptno  Total_salary  Maximun_salary  Minimum_salary  employees count
0      10        426545           74363            1000                9
1      20        477820           74625            2000                9
2      30        536809           70986           60933                8
3      40        545880           72534           63559                8
4      50        570135           78005           62497                8
5      60        525908           71892           59843                8

In [113]:
df = pd.read_csv("emp_details.csv")

In [120]:
df.sort_values(by=['deptno','year'])
# 10,2020 1
# 10 2022 3
# 10 nan 5

     eno               ename         doj  deptno  salary    year
18  1019          Meera Nair  2020-09-17      10    1000  2020.0
2   1001        Arjun Sharma  2022-01-15      10    1000  2022.0
6   1007         Vijay Singh  2022-07-08      10    1000  2022.0
12  1013      Shivani Sharma  2022-09-13      10   74363  2022.0
20  1021      Prakash Pillai  2022-12-11      10   73569     NaN
26  1027       Harshit Kumar  2022-08-16      10   66535     NaN
32  1033         Suresh Jain  2021-12-01      10   69234     NaN
38  1039          Ajit Reddy  2022-04-18      10   69399     NaN
44  1045        Pankaj Joshi  2022-06-10      10   70445     NaN
7   1008         Ananya Iyer  2021-03-15      20   74625  2021.0
1   1002         Priya Patel  2023-03-22      20   67387  2023.0
13  1014         Harish Nair  2023-04-01      20   61487  2023.0
19  1020         Krishna Rao  2023-10-02      20    2000  2023.0
21  1022  Aishwarya Deshmukh  2021-07-25      20   69746     NaN
27  1028       Kanika Thakur  2020-01-10      20   67752     NaN
33  1034          Sonal Shah  2023-08-13      20    2000     NaN
39  1040     Pratibha Sharma  2021-09-05      20   65072     NaN
45  1046          Suman Iyer  2023-04-28      20   67751     NaN
8   1009        Manish Joshi  2020-12-19      30   67560  2020.0
0   1003          Ravi Kumar  2021-05-10      30   70421  2021.0
14  1015         Komal Yadav  2021-11-23      30   61894  2021.0
22  1023          Vikas Soni  2020-11-15      30   60933     NaN
28  1029      Arvind Agarwal  2023-02-18      30   70986     NaN
34  1035       Jayesh Bansal  2020-02-15      30   69811     NaN
40  1041     Subodh Tripathi  2020-05-14      30   68215     NaN
46  1047         Sunil Verma  2020-09-14      30   66989     NaN
3   1004         Sneha Gupta  2020-08-25      40   68902  2020.0
15  1016          Ajay Bhatt  2020-04-25      40   70109  2020.0
9   1010         Simran Kaur  2023-01-11      40   68902  2023.0
23  1024          Ritu Mehra  2023-05-20      40   67801     NaN
29  1030         Divya Singh  2021-04-22      40   67845     NaN
35  1036        Shweta Yadav  2021-06-03      40   63559     NaN
41  1042        Sunita Gupta  2023-03-09      40   72534     NaN
47  1048       Meenal Pandey  2021-07-03      40   66228     NaN
10  1011        Rajesh Mehta  2021-09-01      50   62497  2021.0
16  1017         Pooja Malik  2022-02-28      50   77450  2022.0
48  1049          Manju Nair  2022-11-17      50   69061  2022.0
4   1005          Anil Reddy  2024-02-13      50   78005  2024.0
24  1025       Nitin Chauhan  2020-03-30      50   66948     NaN
30  1031        Akash Prasad  2020-06-05      50   72594     NaN
36  1037      Rajendra Joshi  2023-11-19      50   73561     NaN
42  1043        Arvind Kumar  2021-08-22      50   70019     NaN
17  1018        Raghav Joshi  2021-06-14      60   62873   201.0
11  1012       Deepika Desai  2020-06-10      60   70179  2020.0
49  1050       Sandeep Yadav  2021-10-12      60   60921  2021.0
5   1006          Neha Verma  2019-11-30      60   59843  2029.0
25  1026        Swati Kapoor  2021-10-05      60   66972     NaN
31  1032          Geeta Rani  2022-09-07      60   63916     NaN
37  1038        Kavita Mehta  2020-07-25      60   71892     NaN
43  1044      Neeraj Agarwal  2020-02-19      60   69312     NaN

In [127]:
# SQL  : select deptno,year ,count(eno) from emp group by deptno,year
df.groupby(['deptno','year'])['eno'].count().reset_index().rename(columns={"eno":"employees count"})

    deptno    year  employees count
0       10  2020.0                1
1       10  2022.0                3
2       20  2021.0                1
3       20  2023.0                3
4       30  2020.0                1
5       30  2021.0                2
6       40  2020.0                2
7       40  2023.0                1
8       50  2021.0                1
9       50  2022.0                2
10      50  2024.0                1
11      60   201.0                1
12      60  2020.0                1
13      60  2021.0                1
14      60  2029.0                1

In [126]:
df

     eno               ename         doj  deptno  salary    year
0   1003          Ravi Kumar  2021-05-10      30   70421  2021.0
1   1002         Priya Patel  2023-03-22      20   67387  2023.0
2   1001        Arjun Sharma  2022-01-15      10    1000  2022.0
3   1004         Sneha Gupta  2020-08-25      40   68902  2020.0
4   1005          Anil Reddy  2024-02-13      50   78005  2024.0
5   1006          Neha Verma  2019-11-30      60   59843  2029.0
6   1007         Vijay Singh  2022-07-08      10    1000  2022.0
7   1008         Ananya Iyer  2021-03-15      20   74625  2021.0
8   1009        Manish Joshi  2020-12-19      30   67560  2020.0
9   1010         Simran Kaur  2023-01-11      40   68902  2023.0
10  1011        Rajesh Mehta  2021-09-01      50   62497  2021.0
11  1012       Deepika Desai  2020-06-10      60   70179  2020.0
12  1013      Shivani Sharma  2022-09-13      10   74363  2022.0
13  1014         Harish Nair  2023-04-01      20   61487  2023.0
14  1015         Komal Yadav  2021-11-23      30   61894  2021.0
15  1016          Ajay Bhatt  2020-04-25      40   70109  2020.0
16  1017         Pooja Malik  2022-02-28      50   77450  2022.0
17  1018        Raghav Joshi  2021-06-14      60   62873   201.0
18  1019          Meera Nair  2020-09-17      10    1000  2020.0
19  1020         Krishna Rao  2023-10-02      20    2000  2023.0
20  1021      Prakash Pillai  2022-12-11      10   73569     NaN
21  1022  Aishwarya Deshmukh  2021-07-25      20   69746     NaN
22  1023          Vikas Soni  2020-11-15      30   60933     NaN
23  1024          Ritu Mehra  2023-05-20      40   67801     NaN
24  1025       Nitin Chauhan  2020-03-30      50   66948     NaN
25  1026        Swati Kapoor  2021-10-05      60   66972     NaN
26  1027       Harshit Kumar  2022-08-16      10   66535     NaN
27  1028       Kanika Thakur  2020-01-10      20   67752     NaN
28  1029      Arvind Agarwal  2023-02-18      30   70986     NaN
29  1030         Divya Singh  2021-04-22      40   67845     NaN
30  1031        Akash Prasad  2020-06-05      50   72594     NaN
31  1032          Geeta Rani  2022-09-07      60   63916     NaN
32  1033         Suresh Jain  2021-12-01      10   69234     NaN
33  1034          Sonal Shah  2023-08-13      20    2000     NaN
34  1035       Jayesh Bansal  2020-02-15      30   69811     NaN
35  1036        Shweta Yadav  2021-06-03      40   63559     NaN
36  1037      Rajendra Joshi  2023-11-19      50   73561     NaN
37  1038        Kavita Mehta  2020-07-25      60   71892     NaN
38  1039          Ajit Reddy  2022-04-18      10   69399     NaN
39  1040     Pratibha Sharma  2021-09-05      20   65072     NaN
40  1041     Subodh Tripathi  2020-05-14      30   68215     NaN
41  1042        Sunita Gupta  2023-03-09      40   72534     NaN
42  1043        Arvind Kumar  2021-08-22      50   70019     NaN
43  1044      Neeraj Agarwal  2020-02-19      60   69312     NaN
44  1045        Pankaj Joshi  2022-06-10      10   70445     NaN
45  1046          Suman Iyer  2023-04-28      20   67751     NaN
46  1047         Sunil Verma  2020-09-14      30   66989     NaN
47  1048       Meenal Pandey  2021-07-03      40   66228     NaN
48  1049          Manju Nair  2022-11-17      50   69061  2022.0
49  1050       Sandeep Yadav  2021-10-12      60   60921  2021.0

In [129]:
grouped_data = df.groupby(['deptno','year'])['eno'].count()

In [136]:
filter = grouped_data.apply(lambda x:x>1)

In [139]:
grouped_data[filter]

deptno  year
10      2022.0    3
20      2023.0    3
30      2021.0    2
40      2020.0    2
50      2022.0    2
Name: eno, dtype: int64

In [149]:
# get me all the depnto where we have total salary > 5,00000

grouped_data = df.groupby('deptno')['salary'].sum()
filter_total_sal = grouped_data.apply(lambda x:x>500000)
grouped_data[filter_total_sal].reset_index().rename(columns = {"salary":"total_salary"})

   deptno  total_salary
0      30        536809
1      40        545880
2      50        570135
3      60        525908

deptno
10    426545
20    477820
30    536809
40    545880
50    570135
60    525908
Name: salary, dtype: int64

In [184]:
grouped_data = df.groupby('deptno')['salary'].sum()
type(grouped_data)
grouped_data

deptno
10    426545
20    477820
30    536809
40    545880
50    570135
60    525908
Name: salary, dtype: int64

In [183]:
grouped_df = grouped_data.reset_index()
type(grouped_df)

pandas.core.frame.DataFrame

In [157]:
filter = grouped_df['salary'] > 500000

In [181]:
grouped_df[filter]

   deptno  salary
2      30  536809
3      40  545880
4      50  570135
5      60  525908

# merging ( SQL join equivalent)

In [170]:
df_emp = pd.read_csv("emp.csv")
df_sal = pd.read_csv("salary.txt")

In [163]:
df_sal

     eno  salary
0   1001   52000
1   1002   61000
2   1003   48000
3   1004   75000
4   1005   56000
5   1006   64000
6   1007   59000
7   1008   67000
8   1009   73000
9   1010   50000
10  1011   62000
11  1012   71000
12  1013   55000
13  1014   58000
14  1015   69000
15  1016   53000
16  1017   57000
17  1018   66000
18  3001   60000
19  3002   72000

In [164]:
df_emp

     eno           ename
0   1002     Isha Sharma
1   1003      Rajiv Nair
2   1001     Aarav Mehta
3   1004     Kavya Reddy
4   1005    Aditya Patel
5   1006      Priya Iyer
6   1007     Arjun Singh
7   1008      Neha Verma
8   1009   Devansh Desai
9   1010    Ananya Joshi
10  1011    Rohan Kapoor
11  1012     Simran Kaur
12  1013      Ayan Dutta
13  1014    Tanya Bansal
14  1015  Manav Malhotra
15  2001      Shruti Rao
16  2002     Kunal Dixit
17  2003     Sanya Dubey
18  2010    Harshit Jain
19  2011    Ritika Ghosh

In [166]:
# Merge Syntax ( inner join/ equi join)
# SQL : select e.eno,e.ename,s.salary from emp as e inner join salary as s on e.eno = s.eno
df_emp.merge(df_sal,on='eno',how='inner')

     eno           ename  salary
0   1002     Isha Sharma   61000
1   1003      Rajiv Nair   48000
2   1001     Aarav Mehta   52000
3   1004     Kavya Reddy   75000
4   1005    Aditya Patel   56000
5   1006      Priya Iyer   64000
6   1007     Arjun Singh   59000
7   1008      Neha Verma   67000
8   1009   Devansh Desai   73000
9   1010    Ananya Joshi   50000
10  1011    Rohan Kapoor   62000
11  1012     Simran Kaur   71000
12  1013      Ayan Dutta   55000
13  1014    Tanya Bansal   58000
14  1015  Manav Malhotra   69000

In [167]:
# Merge Syntax ( left outer join)
# SQL : select e.eno,e.ename,s.salary from emp as e left join salary as s on e.eno = s.eno
df_emp.merge(df_sal,on='eno',how='left')

     eno           ename   salary
0   1002     Isha Sharma  61000.0
1   1003      Rajiv Nair  48000.0
2   1001     Aarav Mehta  52000.0
3   1004     Kavya Reddy  75000.0
4   1005    Aditya Patel  56000.0
5   1006      Priya Iyer  64000.0
6   1007     Arjun Singh  59000.0
7   1008      Neha Verma  67000.0
8   1009   Devansh Desai  73000.0
9   1010    Ananya Joshi  50000.0
10  1011    Rohan Kapoor  62000.0
11  1012     Simran Kaur  71000.0
12  1013      Ayan Dutta  55000.0
13  1014    Tanya Bansal  58000.0
14  1015  Manav Malhotra  69000.0
15  2001      Shruti Rao      NaN
16  2002     Kunal Dixit      NaN
17  2003     Sanya Dubey      NaN
18  2010    Harshit Jain      NaN
19  2011    Ritika Ghosh      NaN

In [168]:
# Merge Syntax ( right outer join)
# SQL : select e.eno,e.ename,s.salary from emp as e right join salary as s on e.eno = s.eno
df_emp.merge(df_sal,on='eno',how='right')

     eno           ename  salary
0   1001     Aarav Mehta   52000
1   1002     Isha Sharma   61000
2   1003      Rajiv Nair   48000
3   1004     Kavya Reddy   75000
4   1005    Aditya Patel   56000
5   1006      Priya Iyer   64000
6   1007     Arjun Singh   59000
7   1008      Neha Verma   67000
8   1009   Devansh Desai   73000
9   1010    Ananya Joshi   50000
10  1011    Rohan Kapoor   62000
11  1012     Simran Kaur   71000
12  1013      Ayan Dutta   55000
13  1014    Tanya Bansal   58000
14  1015  Manav Malhotra   69000
15  1016             NaN   53000
16  1017             NaN   57000
17  1018             NaN   66000
18  3001             NaN   60000
19  3002             NaN   72000

In [177]:
# Merge Syntax ( inner join)
# SQL : select e.eid,e.ename,s.salary from emp as e inner join salary as s on e.eid = s.eno
df_emp.merge(df_sal,left_on='eid',right_on='eno',how='inner')

     eid           ename   eno  salary
0   1002     Isha Sharma  1002   61000
1   1003      Rajiv Nair  1003   48000
2   1001     Aarav Mehta  1001   52000
3   1004     Kavya Reddy  1004   75000
4   1005    Aditya Patel  1005   56000
5   1006      Priya Iyer  1006   64000
6   1007     Arjun Singh  1007   59000
7   1008      Neha Verma  1008   67000
8   1009   Devansh Desai  1009   73000
9   1010    Ananya Joshi  1010   50000
10  1011    Rohan Kapoor  1011   62000
11  1012     Simran Kaur  1012   71000
12  1013      Ayan Dutta  1013   55000
13  1014    Tanya Bansal  1014   58000
14  1015  Manav Malhotra  1015   69000

In [172]:
# What if the common keys are having different names in both the data frames
# SQL : select e.eno,e.ename,s.salary from emp as e full join salary as s on e.eno = s.eno

#df_emp.merge(df_sal,on='eno',how='outer')

     eno  salary
0   1001   52000
1   1002   61000
2   1003   48000
3   1004   75000
4   1005   56000
5   1006   64000
6   1007   59000
7   1008   67000
8   1009   73000
9   1010   50000
10  1011   62000
11  1012   71000
12  1013   55000
13  1014   58000
14  1015   69000
15  1016   53000
16  1017   57000
17  1018   66000
18  3001   60000
19  3002   72000

Assignment

# Doubt session

Assigenement

In [4]:
import pandas as pd

In [6]:
df = pd.read_csv("employee.csv")

In [26]:
## SQL equivalent : select depnto,count(deptno) from emp group by deptno
emp_count_by_deptno =df.groupby('deptno')['eno'].count().reset_index()
emp_count_by_deptno.rename(columns = {'eno':'emp_count'},inplace=True)

emp_count_by_deptno

   deptno  emp_count
0      10          5
1      20          2
2      30          4

In [32]:
# SQL query : select deptno,sum(salary) from emp group by depnto
emp_cosalary_by_deptno =df.groupby('deptno')['salary'].sum().reset_index()
emp_cosalary_by_deptno

   deptno  salary
0      10    6000
1      20    4000
2      30   47000

In [38]:
# final SQL query : select deptno,sum(salary) from emp where salary < 10000 group by depnto
emp_lesee_salary = emp_cosalary_by_deptno['salary'] < 10000
emp_rename = emp_cosalary_by_deptno[emp_lesee_salary].rename(columns = {'salary':'total_salary'})
emp_rename

   deptno  total_salary
0      10          6000
1      20          4000

In [40]:
# sql : select deptno,count(eno),sum(salary),max(deptno) from emp group by deptno
df.groupby('deptno').agg({'eno':'count','salary':'sum','deptno':'max'})

        eno  salary  deptno
deptno
10        5    6000      10
20        2    4000      20
30        4   47000      30

#Assignment 2